### ISSUE TITLE
SSE2 instruction set not enabled

### ISSUE THREAD

**Issue by raarts** [mwarning/zerotier-openwrt#1]
Hi,

This would not compile for me, I get the following:
```
In file included from node/Salsa20.hpp:20:0,
                 from node/Identity.cpp:36:
/home/raarts/openwrt/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_uClibc-0.9.33.2/lib/gcc/i486-openwrt-linux-uclibc/4.8.3/include/emmintrin.h:31:3: error: #error "SSE2 instruction set not enabled"
 # error "SSE2 instruction set not enabled"
   ^
In file included from node/Identity.cpp:36:0:
node/Salsa20.hpp:82:3: error: '__m128i' does not name a type
   __m128i v[4];
   ^
```
Now I can disable SSE2 in the zerotier-one Makefile, by just removing it, but I am wondering why it compiled for you.

**Comment by mwarning** [comment]
That is odd. I compiles for me.
I use Debian 8.0 right now and OpenWrt 14.07 (Barrier Breaker).
Did you disable it by adding  -mno-sse?

**Comment by raarts** [comment]
Hi,

I re-did everything, but same problem. Note I chose the x86 Target, because
I run it on virtualbox.

Ron

**Comment by raarts** [comment]
BTW, I am an openwrt noob, so I wouldn't know where to specify -mno-sse

**Comment by mwarning** [comment]
I think the x86 target is the "culprit". Zerotier probably enables sse2 for x86. I will do some testing. Thanks for the find!

**Comment by raarts** [comment]
By the way, I had to install gettext as well, you might want to add that to the apt-get line in README.md

**Comment by mwarning** [comment]
Both issues should be fixed now. Thanks a lot for reporting!
