### ISSUE TITLE
Backport 1.10.1 to OpenWRT 22.03

### ISSUE THREAD

**Issue by olfway** [mwarning/zerotier-openwrt#106]
Is it possible to backport latest zerotier? OpenWRT 22.03 only has 1.8.6 now

Thanks!

**Comment by mwarning** [comment]
Yes, that should be possible. I will take a look next week.

**Comment by mwarning** [comment]
Let's see https://github.com/openwrt/packages/pull/19409

**Comment by olfway** [comment]
thanks!

**Comment by daliangdaliang** [comment]
openwrt 22.03 以后采取了nft的防火墙设置，这导致原来的iptable配置可能失效了。请问这个该如何适应调整呢？

openwrt adopted the nft firewall Settings after 22.03. As a result, the original iptable configuration may be invalid. Could you please tell me how to adjust this?

**Comment by mwarning** [comment]
What original iptables configuration do you refer to?

**Comment by daliangdaliang** [comment]
iptables -I FORWARD -i zt7nnafjol -j ACCEPT
iptables -I FORWARD -o zt7nnafjol -j ACCEPT
iptables -t nat -I POSTROUTING -o zt7nnafjol -j MASQUERADE

The new version does not have the space to paste the above three lines of commands.


![2023-03-09_122935](https://user-images.githubusercontent.com/8480556/223917442-85119a70-380f-43e5-9b21-09ff67dcc45f.png)


![2023-03-09_122949](https://user-images.githubusercontent.com/8480556/223917468-295427f5-777f-48ac-8256-a7f4b0d19776.png)

**Comment by ogarcia** [comment]
@mwarning I believe this issue can be closed since the original question is resolved. @daliangdaliang if you still have problems open a new issue and let us know what they are.
