### ISSUE TITLE
cannot access devices on LAN after follow thru the installation guide. 

### ISSUE THREAD

**Issue by vinch9292** [mwarning/zerotier-openwrt#112]
i follow the exact instruction here to setup the zerotier on router with openwrt 22.xx. I can only access and ping the router only, but not devices within the local LAN network. i had search all over the internet but still didn't find any workable solutions.
please kindly help.
Thanks

**Comment by ogarcia** [comment]
With the information you provide it is a bit complicated to help you. I advise you to [reread the wiki](https://github.com/mwarning/zerotier-openwrt/wiki) (especially the part [Configure the routing within OpenWRT](https://github.com/mwarning/zerotier-openwrt/wiki#configure-the-routing-within-openwrt)) and reproduce step by step what it indicates, if you do it as it should work.

**Comment by vinch9292** [comment]
thanks for the help. i did checked "Allow Ethernet Bridging" for the router, but do I also need to check AEB for external ZT clients?

**Comment by vinch9292** [comment]
RDP to the windows is working but still cant access the NAS. NAS was setup for intranet only, no internet connection. the idea was to remote access the NAS locally through ZT.

**Comment by ogarcia** [comment]
You may have a firewall on your NAS that only allows connections from the range of your local network. You have to allow also in that firewall the range of your Zerotier network for everything to work.
