### ISSUE TITLE
Openwrt does not support allocating ipv6 prefixes of ZeroTier "6PLANE" (/80 routable for each device) with a length of 80.

### ISSUE THREAD

**Issue by masx200** [mwarning/zerotier-openwrt#116]
Openwrt does not support allocating ipv6 prefixes of ZeroTier "6PLANE" (/80 routable for each device) with a length of 80.

/etc/config/network
```
config interface 'zerotier'
	option proto 'static'
	option device 'ztfp6ef2gf'
	option ipaddr '10.242.195.152'
	option netmask '255.255.0.0'
	list ip6addr 'fc1d:c6a6:f3ef:8c4b:1eb3::1/40'
	list ip6addr 'fd52:b337:794f:7591:8a99:93ef:8c4b:1eb3/88'
	option ip6prefix 'fc1d:c6a6:f3ef:8c4b:1eb3::1/80'
```

OpenWrt 23.05.2 r23630-842932a63d / LuCI openwrt-23.05 branch git-23.306.39416-c86c256

**Comment by ogarcia** [comment]
ZeroTier in OpenWrt does not support static configuration, only unmanaged configuration works in this way:
```
config interface 'zerotier'
	option proto 'none'
	option device 'ztfp6ef2gf'
```

If you want to configure the IP to the network it is best to do it from ZeroTier Central and then the router will automatically take this configuration.
