### ISSUE TITLE
Use openwrt with zerotier as a gateway

### ISSUE THREAD

**Issue by ganganrobert** [mwarning/zerotier-openwrt#117]
I want to use my router with zerotier as a gateway for other devices, I did settings as it mentioned in this [https://github.com/mwarning/zerotier-openwrt/wiki](url)  ,but I get Ip address from my mobile isp. I can access to the 192.168.1.1, but not the gateway throw my router. Is it possible to have the same ip in mobile phone as a router ip?

**Comment by ogarcia** [comment]
If I understand correctly what you want to do is that all your systems connect to the Internet through your router and using the ZeroTier network. This is possible to do, but for this you have to, in the clients that are not your router, set the option `allowDefault` to 1 to tell them that they must route all their traffic through the ZeroTier network.

See [here](https://docs.zerotier.com/config/#network-specific-configuration) and [here](https://zerotier.atlassian.net/wiki/spaces/SD/pages/7110693/Overriding+Default+Route+Full+Tunnel+Mode) for more information.
