### ISSUE TITLE
Can't ping some of the  devices behind router

### ISSUE THREAD

**Issue by Xiaoran134** [mwarning/zerotier-openwrt#121]
Hi,
I've installed zerotier on my router, which runs a  openWRT. I've followed the instructions, set up openwrt's firewall, also set up the settings on Zerotier's Network console page.

The router's Zerotier VPN ip is set to 192.168.192.1, It's LAN IP is 192.168.88.1. Here's the problem:

I can ping the router‘s LAN IP with a smart phone connected to the Zerotier VPN（which use smartphone's cellular data）, I can even ping  an AP under the router using it's LAN IP. But when I try to access the PC's smb service (windows 11)  behind the router, I falled. Also it's posible to ping the smart phone's Zerotier ip from the PC, but I cannt ping the PC from my smart phone. 

Both the AP an PC belongs to 192.168.88.0/24, and thier Zerotier VPN IP belongs to 192.168.192.0/24

I wonder if it's the windows's firewall that blocks me from accessing it, but I don't how to solve it.

**Comment by ogarcia** [comment]
Have you tried [disabling the Windows firewall completely](https://support.microsoft.com/en-us/windows/turn-microsoft-defender-firewall-on-or-off-ec0844f7-aebd-0583-67fe-601ecf5d774f)? Because everything certainly points to that.

Another test you can do is to boot with a USB in LIVE mode with a Linux distribution and thus rule out the possible problems that Windows is causing you.

**Comment by Xiaoran134** [comment]
> Have you tried [disabling the Windows firewall completely](https://support.microsoft.com/en-us/windows/turn-microsoft-defender-firewall-on-or-off-ec0844f7-aebd-0583-67fe-601ecf5d774f)? Because everything certainly points to that.
> 
> Another test you can do is to boot with a USB in LIVE mode with a Linux distribution and thus rule out the possible problems that Windows is causing you.

Thanks! I’ve just tried disabling Windows firewall, and everything turns normal ! 
But I'm not sure if it's safe to disable the firewall,  since I'm not familliar to this field.  If I want to keep using Windows System, what rules should I set to Windows firewall ?

**Comment by ogarcia** [comment]
> But I'm not sure if it's safe to disable the firewall, since I'm not familliar to this field. If I want to keep using Windows System, what rules should I set to Windows firewall ?

I can't help you there because I don't use Windows and I don't know exactly why it cuts those accesses. I suppose it has to do with the fact that it does not like to receive requests from a network (192.168.192.0/24) that is not its own (192.168.88.0/24).

**Comment by Xiaoran134** [comment]
> > But I'm not sure if it's safe to disable the firewall, since I'm not familliar to this field. If I want to keep using Windows System, what rules should I set to Windows firewall ?
> 
> I can't help you there because I don't use Windows and I don't know exactly why it cuts those accesses. I suppose it has to do with the fact that it does not like to receive requests from a network (192.168.192.0/24) that is not its own (192.168.88.0/24).

Okay, Thanks.! I just set an inbound rule for 192.168.192.0/24, seems everything's right
