### ISSUE TITLE
error on /etc/init.d/zerotier restart

### ISSUE THREAD

**Issue by mikysal78** [mwarning/zerotier-openwrt#126]
Hi, i have this error on restart from "/etc/init.d/zerotier restart"

disabled in /etc/config/zerotier
Generating secret - please wait... uci: invalid argument
done.
/etc/rc.common: line 81: can't create /var/lib/zerotier-one/identity.secret: nonexistent directory

how-to solve?
With the old version everything was ok

Thanks.

**Comment by ogarcia** [comment]
I just uploaded a merge request (#127) that solves the problem. If you can try that I would be very grateful.
