### ISSUE TITLE
A misprint in the Wiki

### ISSUE THREAD

**Issue by alekvol** [mwarning/zerotier-openwrt#134]
On the "Configure ZeroTier routing in OpenWRT" page, the link to the IP address of the zt interface on the OpenWRT router is incorrect.
![Снимок экрана 2024-10-10 033909](https://github.com/user-attachments/assets/5f78cd0c-8c73-427b-a9af-8258c5b84bb1)
It should be 172.28.28.1, thanks)

**Comment by ogarcia** [comment]
@alekvol fixed! Thanks!! :-)
