### ISSUE TITLE
Where is the `identity.public` file needed for setting up a moon server?

### ISSUE THREAD

**Issue by dzx-dzx** [mwarning/zerotier-openwrt#136]
Per https://github.com/mwarning/zerotier-openwrt/issues/60 we should be able to start a moon server on an Openwrt route, but under the configuration path `/var/lib/zerotier-one` there only exists `identity.secret`.

My zerotier version on this route is `1.12.2`. I had wrongly followed the steps for [newer](https://github.com/mwarning/zerotier-openwrt/wiki/Configure-ZeroTier-on-OpenWrt) versions. It has since been corrected with the secret regenerated.

**Comment by ogarcia** [comment]
To make this configuration more advanced you need to create a directory where you want (for example `/etc/zerotier`) and put in it the files you are interested in. Then in the zerotier configuration you do something like this:
```
config zerotier 'global'
	option enabled '1'
	option config_path '/etc/zerotier'
	option copy_config_path '1'
	option secret 'yoursecret'

config network 'yournetwork'
	option id 'networkid'
```

This way when the Zerotier daemon is started the configuration in `/etc/zerotier` will be copied to its destination and it will start with that configuration.

For example, in `/etc/zerotier` you can create the `moons.d` directory, put all the moons configuration inside and, when you start, you will see that it takes that configuration.

**Comment by dzx-dzx** [comment]
@ogarcia Thanks for replying! But... I want the route itself to be a moon server, instead of adding known moon server to it?

Also while digging into the code, I wonder what the following line does:
https://github.com/mwarning/zerotier-openwrt/blob/03a8b3c7288db15b176ed074a8433fddcf285464/zerotier/files/etc/init.d/zerotier#L88

**Comment by ogarcia** [comment]
Ah, you say that because you don't have the identity.public. You get that simply by running `zerotier-idtool getpublic identity.secret`. :wink:

Or from anywhere: `zerotier-idtool getpublic /var/lib/zerotier-one/identity.secret`

**Comment by dzx-dzx** [comment]
I'd try now, thanks!

**Comment by ogarcia** [comment]
Ok. When you solve the problem please don't forget to close the issue. :wink:

**Comment by dzx-dzx** [comment]
The moon server is ready. Thank again!

To give those who've come to this issue a heads-up: You could fail to set up the moon server even you received `200 orbit`. Refer to [this](https://github.com/zerotier/ZeroTierOne/issues/2197#issuecomment-1945499054) and make sure that all files and directories are present and named correctly.
