### ISSUE TITLE
Mikrotik

### ISSUE THREAD

**Issue by zombiespawn** [mwarning/zerotier-openwrt#16]
Hi there, 

Would this be able to be ported to a Mikrotik (RouterOS) package

Regards,

**Comment by mwarning** [comment]
@zombiespawn yes, I think so. But I do not have any experience with RouterOS.

**Comment by cabsandy** [comment]
How difficult/how much work would it be to have the pre-built images updated to the latest 1.2.4 version? I'd like to have a go if it is too much work, if someone points me in the right direction :-)

**Comment by mwarning** [comment]
I do not know anything about RouterOS except that it is linux based..
So far lede-project.net (openwrt fork/heir) has packages for ZeroTier 1.2.4 and images for many mikrotik devices.

**Comment by cabsandy** [comment]
Ahh sorry-should have put this in a seperate post-I meant for ALL types of HW-so not just Router OS.Sorry.
