### ISSUE TITLE
The CPU utilization reaches more than 75%  when I forward traffic using zt interface 

### ISSUE THREAD

**Issue by tamilhce** [mwarning/zerotier-openwrt#17]
I have installed zerotier in my openwrt Access Point.
And created tunnel interface zt between two devices   and run the iperf test. 
I could see the zerotier  takes more than 75% cpu. I believe its not recommended.
Any suggestion to reduce the cpu utilization  is much appreciated.

> -Load average: 0.68 0.29 0.18 3/57 1176
  PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
 1062     1 root     R    16456  13%  77% /usr/bin/zerotier-one
 1176   406 root     R     1204   1%   0% top
    3     2 root     SW       0   0%   0% [ksoftirqd/0]
 1146     1 dnsmasq  S     1068   1%   0% /usr/sbin/dnsmasq -C /var/etc/dnsmasq
  847     1 mosquitt S     3172   3%   0% mosquitto -c /etc/mosquitto/mosquitto
  683     1 nobody   S     2260   2%   0% /usr/sbin/mdnsd -debug
  590     1 root     S     1696   1%   0% /sbin/netifd
    1     0 root     S     1540   1%   0% /sbin/procd
  616     1 root     S     1428   1%   0% /usr/sbin/odhcpd
  539     1 root     S     1236   1%   0% /sbin/logd -S 64
  406     1 root     S     1208   1%   0% /bin/ash --login
  727   590 root     S     1204   1%   0% udhcpc -p /var/run/udhcpc-eth0.2.pid
  405     1 root     S     1188   1%   0% /sbin/ubusd
  775     1 root     S     1176   1%   0% /usr/bin/mDNSResponder -b -f /etc/mDN
  646     1 root     S     1068   1%   0% /usr/sbin/dropbear -F -P /var/run/dro
  737   590 root     S     1028   1%   0% odhcp6c -s /lib/netifd/dhcpv6.script
  241     2 root     SW       0   0%   0% [kworker/1:1]
  143     2 root     SW       0   0%   0% [kworker/0:1]
  240     2 root     SW       0   0%   0% [spi32766]
  355     2 root     SWN      0   0%   0% [jffs2_gcd_mtd6]

**Comment by tamilhce** [comment]
yes my cpu is not powerful. Can I have steps to  compile zt for speed instead of size.
Thanks in Advance

**Comment by mwarning** [comment]
I do not know.
I asked the question here: https://forum.lede-project.org/t/disable-size-optimization-0s-for-package/5150/1
