### ISSUE TITLE
X86 or X64 prebuild package ?

### ISSUE THREAD

**Issue by forhuan** [mwarning/zerotier-openwrt#19]
I'm using LEDE-X64 , but there is no prebuild package for x86 or x64

**Comment by mwarning** [comment]
Ok, time to build some packages:
https://github.com/mwarning/zerotier-openwrt/releases/tag/v1.2.4_2

The package will be attached there as soon they have finished building.

**Comment by forhuan** [comment]
thanks

**Comment by fanthos** [comment]
I am running LEDE x64, but seems that x86 package not usable on my device. Can you also build it for x64?

**Comment by mwarning** [comment]
I have added the package. See https://github.com/mwarning/zerotier-openwrt/releases/tag/v1.2.6_1
