### ISSUE TITLE
Identity not preserved across reboots

### ISSUE THREAD

**Issue by raarts** [mwarning/zerotier-openwrt#2]
When joining a network, the zerotier daemon writes some info into /var/lib/zerotier/identity.*
This needs to be preserved across reboots, so now every time the device reboots it shows
up on the zerotier website as a new device.

**Comment by raarts** [comment]
I am not an openwrt expert, but I think this info should be stored using UCI? I'm willing to create the patch, but I don't want to duplicate work, especially since you seem to be much more experienced with openwrt.

**Comment by mwarning** [comment]
Please go ahead and write a patch. I haven't done any more work in this area. :)

**Comment by mwarning** [comment]
Fixed now. It will be in the next release package.
