### ISSUE TITLE
libminiupnpc.so.16 is missing in zerotier (1.2.4-2)

### ISSUE THREAD

**Issue by gutleib** [mwarning/zerotier-openwrt#20]
`Error loading shared library libminiupnpc.so.16: No such file or directory (needed by /usr/bin/zerotier-cli)`

Sorry, late night hacking leads to poor judgement.
Additional info:
ver. of OS is LEDE 17.01.4 
arch is MIPS MIPS 74Kc, installing on top of v1.1.14, 
```
Installing libminiupnpc (1.9-1) to root...
Downloading http://downloads.lede-project.org/releases/17.01.4/packages/mips_24kc/packages/libminiupnpc_1.9-1_mips_24kc.ipk
```
so, thats new.

**Comment by mwarning** [comment]
yes, I should add that some libraries need to be installed as well.

**Comment by mwarning** [comment]
Let me know if other packages have to be installed as well.
I wonder why the dependency is not recognized by opkg...

**Comment by gutleib** [comment]
Actually, dependencies are resolved:
```
opkg install zerotier_1.2.4-2_mips_24kc.ipk 
Upgrading zerotier on root from 1.1.14-4 to 1.2.4-2...
Installing libstdcpp (5.4.0-1) to root...
Downloading http://downloads.lede-project.org/releases/17.01.4/targets/ar71xx/generic/packages/libstdcpp_5.4.0-1_mips_24kc.ipk
Installing libminiupnpc (1.9-1) to root...
Downloading http://downloads.lede-project.org/releases/17.01.4/packages/mips_24kc/packages/libminiupnpc_1.9-1_mips_24kc.ipk
Installing libnatpmp (20140401-1) to root...
Downloading http://downloads.lede-project.org/releases/17.01.4/packages/mips_24kc/packages/libnatpmp_20140401-1_mips_24kc.ipk
Configuring libstdcpp.
Configuring libminiupnpc.
Configuring libnatpmp.
Configuring zerotier.
Generate secret - please wait...
Error loading shared library libminiupnpc.so.16: No such file or directory (needed by /usr/bin/zerotier-idtool)
cat: can't open '/tmp/zt.sample_config.secret': No such file or directory
rm: can't remove '/tmp/zt.sample_config.secret': No such file or directory
```
The problem is, the file is not in the package. File mentioned in error messsage is `libminiupnpc.so.16`, and I got `/usr/lib/libminiupnpc.so.10`

**Comment by mwarning** [comment]
Hm, I will have to look into this problem tomorrow. Time to sleep.

**Comment by mwarning** [comment]
@gutleib I have rebuild the packages. Please give it a try. I cannot test right now.

**Comment by gutleib** [comment]
Is the change in source code, or in the release?

**Comment by mwarning** [comment]
I've updated all packages from the openwrt-package feed to the most recent state. That caused the dependency on a newer miniupnpc version. But I should have updated only the zerotier package.

**Comment by gutleib** [comment]
Cool.
But what I've asked was, can I just use your release files, or do I have to compile (sorry, I have no experience with feeds and building custom firmware)?

**Comment by gutleib** [comment]
Nevermind previous question.

I've checked it, and it seems to work perfectly.
Thanks & keep up great work!
