### ISSUE TITLE
Could you please build a mipselsf version for routers with CPU MT7620(or MT7621)?

### ISSUE THREAD

**Issue by hbxntsxw** [mwarning/zerotier-openwrt#24]
My router's CPU is MT7621, I have tried all the versions from the release page. But none of them could install. 

Below is the feedback:
[RT-N56U_B1 /opt/home/admin]# opkg install /tmp/zerotier_*.ipk
Package zerotier version 1.2.4-2 has no valid architecture, ignoring.

**Comment by mwarning** [comment]
Please try https://github.com/mwarning/zerotier-openwrt/releases/download/v1.2.4_2/zerotier_1.2.4-2_mipsel_74kc.ipk

**Comment by hbxntsxw** [comment]
Thank you very much!

**Comment by mwarning** [comment]
ok, closing the ticket for now.

**Comment by lucktu** [comment]
My route isn't working too!
The CPU is MTK7620A, building is "Gargoyle | OpenWrt Chaos Calmer 15.05.1 r49577".
I try "v1.2.4_2/zerotier_1.2.4-2_mipsel_74kc.ipk", get
`root@Gargoyle:/tmp# opkg install zerotier_1.2.4-2_mipsel_74kc.ipk
Preparing to install the following packages, which will require 742966 bytes:
        libstdcpp, libnatpmp, zerotier, libminiupnpc

Preparing to install package libstdcpp...
        Downloading...
ERROR: Expected MD5Sum for libstdcpp not specified, cannot verify package
An error occurred during Installation, removing partially installed packages.
Removing package libstdcpp...
Finished removing libstdcpp.

Removing package zerotier...
Finished removing zerotier.

Finished removing partially installed packages.
`
I have to using "zerotier_1.1.0-1_ramips_24kec.ipk" & "zerotier_1.0.5-1_ramips_24kec.ipk".but it's too old to not using moon.

so i want to using the newest ipk very.

**Comment by mwarning** [comment]
Can't you use an openwrt snapshot? https://downloads.lede-project.org/snapshots/targets/
`opkg update` and `opkg install zerotier` should do it.

**Comment by lucktu** [comment]
@mwarning 
no,nothing. https://downloads.lede-project.org/snapshots/targets/
but it's here, http://archive.openwrt.org/snapshots/trunk/ramips/mt7620/packages/packages/
--------------------------------------------------------------------------------------
I am sorry, installing:
root@Gargoyle:~# opkg install zerotier
Preparing to install the following packages, which will require 740501 bytes:
        libstdcpp, libnatpmp, zerotier, libminiupnpc

Preparing to install package libstdcpp...
        Downloading...
        Downloaded libstdcpp successfully.
        Installing libstdcpp...
        Successfully installed libstdcpp.
Preparing to install package libnatpmp...
        Downloading...
        Downloaded libnatpmp successfully.
        Installing libnatpmp...
        Successfully installed libnatpmp.
Preparing to install package libminiupnpc...
        Downloading...
        Downloaded libminiupnpc successfully.
        Installing libminiupnpc...
        Successfully installed libminiupnpc.
Preparing to install package zerotier...
        Downloading...
        Downloaded zerotier successfully.
        Installing zerotier...
Generate secret - please wait...
/etc/rc.common: eval: line 1: zerotier-idtool: not found
cat: can't open '/tmp/zt.sample_config.secret': No such file or directory
rm: can't remove '/tmp/zt.sample_config.secret': No such file or directory
        Successfully installed zerotier.
Installation of packages successful.
root@Gargoyle:~# zerotier-cli -h
-ash: zerotier-cli: not found

**Comment by mwarning** [comment]
I tested https://downloads.lede-project.org/snapshots/targets/ramips/mt7620/openwrt-ramips-mt7620-wt3020-8M-squashfs-sysupgrade.bin
```
root@OpenWrt:~# opkg install zerotier
Installing zerotier (1.2.4-2) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/mipsel_24kc/packages/zerotier_1.2.4-2_mipsel_24kc.ipk
Installing libstdcpp (5.5.0-1) to root...
Downloading http://downloads.lede-project.org/snapshots/targets/ramips/mt7620/packages/libstdcpp_5.5.0-1_mipsel_24kc.ipk
Installing kmod-tun (4.9.76-1) to root...
Downloading http://downloads.lede-project.org/snapshots/targets/ramips/mt7620/packages/kmod-tun_4.9.76-1_mipsel_24kc.ipk
Installing libminiupnpc (2.0.20170509-1) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/mipsel_24kc/packages/libminiupnpc_2.0.20170509-1_mipsel_24kc.ipk
Installing libnatpmp (20140401-1) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/mipsel_24kc/packages/libnatpmp_20140401-1_mipsel_24kc.ipk
Configuring kmod-tun.
Configuring libstdcpp.
Configuring libminiupnpc.
Configuring libnatpmp.
Configuring zerotier.
Generate secret - please wait...
root@OpenWrt:~#
```

Works for me.

**Comment by lucktu** [comment]
yes, lede is ok, but not for openwrt cc.

**Comment by mwarning** [comment]
OpenWrt 15.05 is very old. Pease use lede (it is merging with OpenWrt now anyway). I can't do much for old OpenWrt versions.

**Comment by lucktu** [comment]
I am sorry, but all come from Official.
https://www.gargoyle-router.com/download.php
http://dl.eko.one.pl/gargoyle-pl/chaos_calmer/ramips/

Otherwise, how about the ipk for entware ?

**Comment by mwarning** [comment]
If the gargoyle project builds there own images, then they should also provide their own packages.
I do not know what openwrt version their images are based on. If it is an old openwrt version, then there is nothing I can do.

**Comment by lucktu** [comment]
OK, I see.
Thank you!
