### ISSUE TITLE
persistent folder and variable paths to be able to run a ZeroTier controller on LEDE

### ISSUE THREAD

**Issue by boschkundendienst** [mwarning/zerotier-openwrt#25]
I am currently experimenting with the ZeroTier controller which is implemented into ZeroTier since Version 1.2 on my LEDE router (OpenWrt SNAPSHOT r5849-5bbcd80) with ZeroTier 1.2.4 on a TP-LINK TL-WDR4300.

Some problems came up.

A controller needs some reboot resistent files so I took a look at the `/etc/init.d/zerotier` script and found a lot of hardcoded paths in there. So I changed them to a variable so I could set my own folder which is not on a tmpfs.

I made the following changes to put all my stuff into `/zerotier` instead of `/tmp` or `/var/lib/zerotier` to make it reboot resistent.

Also I added an additional argument to the appropriate calls to ZeroTier binaries to specify the working directory.

IMHO this change **this change should be implemented in the zerotier init script to avoid hardcoded paths** and it would be great if an expert could maybe add an option to define the zerotier configuration path via `uci config zerotier` which should be possible with the changes below.

Here are my changes to `/etc/init.d/zerotier`

`diff zerotier.new zerotier.org`

~~~
10d9
< ZT_FOLDER=/zerotier
21c20
<       local LASTARG="$ZT_FOLDER"
---
>
24c23
<       mkdir -p $ZT_FOLDER/networks.d/
---
>       mkdir -p /var/lib/zerotier-one/networks.d/
31c30
<               ARGS="$ARGS -p$port $LASTARG"
---
>               ARGS="$ARGS -p$port"
46c45
<               echo "$secret" > $ZT_FOLDER/identity.secret
---
>               echo "$secret" > /var/lib/zerotier-one/identity.secret
48c47
<               rm -f $ZT_FOLDER/identity.public
---
>               rm -f /var/lib/zerotier-one/identity.public
53c52
<               touch $ZT_FOLDER/networks.d/$1.conf
---
>               touch /var/lib/zerotier-one/networks.d/$1.conf
60c59
<       procd_set_param command $ZT_COMMAND $ARGS $LASTARG
---
>       procd_set_param command $ZT_COMMAND $ARGS
~~~

**Comment by mwarning** [comment]
Sure, that can be done and isn't much work. But keep in mind that writing into the flash might degrade the chip.
Wouldn't it be possible to keep all static data in /etc/config/zerotier?

**Comment by mwarning** [comment]
What information need to be stored for the network controller? Is the network controller a suitable task for a openwrt router?

**Comment by boschkundendienst** [comment]
I think the router can handle it. Having your own controller (currently only configurable via API using Json requests) has the benefit, that you would not need an account at zerotier.com. You would only use their backend as a kind of phonebook like DNS. All members of your network (you host via the controller) will use the information from the controller to connect or use the controller as router (and not zerotier central). - So result will be higher speeds and lower latency.
This is nearly the same as they offer with their device they sell but without the wunderful graphical interface. Think about it as having my.zerotier.com on your router but only configurable via json requests against the API authenticated by your API-secret (also lying arround in the config dir).

Let me take a look into the controller stuff when I have time and give more feedback.

The most important directory is

`/<configdir>/controller.d/`

afaik.

Documentation can be found here:
https://github.com/zerotier/ZeroTierOne/tree/master/controller

**Hint:**
When following the documentation when they talk about **POST to /controller/network/##########______** you have to fill in the clientID of the router for the # and at the end 6 x `_`.
Then a network is created in the format

<yourclientid><random6digitsafterwards>

All future request then have to use the network ID that has been created.

And this is then stored in the controller configuration which we need reboot resistent.

**Comment by boschkundendienst** [comment]
`>Wouldn't it be possible to keep all static data in /etc/config/zerotier?`
This might be possible if we could re-create the ZeroTier working folder with all necessary files containing the secrets and configuration (also for the controller) from config file. But afaik now they are not all just text files some are small databases I think.
Of course this would be better for keeping the router alive for a  long time not degrading the chip.

**Comment by mwarning** [comment]
I have implemented a few changes to make the configuration path configurable: https://github.com/mwarning/zerotier-openwrt/commit/d82d87976a0222fd4e95d7349d0a288ef7fb9f3e
If it works, we can submit it to https://github.com/openwrt/packages/.

**Comment by boschkundendienst** [comment]
Changes look good, could not test, yet. We should keep in mind, when someone has changed the configuration folder also zerotier-cli needs the path as parameter.

~~~
-D<path>                - ZeroTier home path for parameter auto-detect
~~~
I am not that familiar with LEDE. If it would be possible, when a custom path is used to automatically alias `zerotier-cli as `zerotier-clie -D<newpath>`, that would be great!

**Comment by mwarning** [comment]
That is why I make a symbolic link from the /var/lib/zerotier-one to the custom path. Works for me.

**Comment by boschkundendienst** [comment]
I can confirm the init script works as expected after adding

~~~
option config_path '<custom configuration path>'
~~~

to `/etc/config/zerotier`

Thanks for that one!

**Comment by nikito7** [comment]
option config_path '/etc/zerotier'

Error if folder dont exist
