### ISSUE TITLE
Need to explicitely join zt net after reboot

### ISSUE THREAD

**Issue by delandtj** [mwarning/zerotier-openwrt#29]
Using latest tree (and also before) I need to explicitely `zerotier-cli join xxxxxxxxxx` after a reboot, or after a `/etc/init.d/zerotier restart`

```
uci delete zerotier.sample_config
uci set zerotier.mgmt_net='zerotier'
uci set zerotier.mgmt_net.enabled=1
uci set zerotier.mgmt_net.join='z2d702236df22344'
uci set zerotier.mgmt_net.secret='generate'
uci commit
```
after restart : no `zt0`

I have to `zerotier-cli join z2d702236df22344` to have `zt0` again.

tried to do that in the `add_join` but no dice

**Comment by mwarning** [comment]
Can you show me your /etc/config/zerotier?
I suspect the problem is that you now have `option join 'generate'` instead of `list join 'generate'`

**Comment by delandtj** [comment]
pffffff....
uci add_list ....
I stand corrected
Jan

**Comment by mwarning** [comment]
NP, I will burry it as deep as I can. xD
