### ISSUE TITLE
Can`t compile for BRCM47xxx

### ISSUE THREAD

**Issue by 2senel** [mwarning/zerotier-openwrt#3]
I followed all instructions and also searched through other forums and found no solution :-(

http://pastebin.com/XGk8HLwe

virtual@virtual-Parallels-Virtual-Platform:~/openwrt$ make
 make[1] world
 make[2] toolchain/install
 make[3] -C toolchain/gdb prepare
 make[3] -C toolchain/gdb compile
 make[3] -C toolchain/gdb install
 make[3] -C toolchain/binutils prepare
 make[3] -C toolchain/binutils compile
 make[3] -C toolchain/binutils install
 make[3] -C toolchain/gcc/minimal prepare
 make[3] -C toolchain/gcc/minimal compile
 make[3] -C toolchain/gcc/minimal install
 make[3] -C toolchain/kernel-headers prepare
 make[3] -C toolchain/kernel-headers compile
 make[3] -C toolchain/kernel-headers install
 make[3] -C toolchain/uClibc/headers prepare
 make[3] -C toolchain/uClibc/headers compile
 make[3] -C toolchain/uClibc/headers install
 make[3] -C toolchain/gcc/initial prepare
 make[3] -C toolchain/gcc/initial compile
 make[3] -C toolchain/gcc/initial install
 make[3] -C toolchain/uClibc prepare
 make[3] -C toolchain/uClibc compile
 make[3] -C toolchain/uClibc install
 make[3] -C toolchain/gcc/final prepare
 make[3] -C toolchain/gcc/final compile
 make[3] -C toolchain/gcc/final install
 make[3] -C toolchain/uClibc/utils prepare
 make[3] -C toolchain/uClibc/utils compile
 make[3] -C toolchain/uClibc/utils install
 make[2] target/compile
 make[3] -C target/linux compile
 make[2] package/cleanup
 make[2] package/compile
 make[3] -C package/libs/toolchain compile
 make[3] -C package/libs/libnl-tiny compile
 make[3] -C package/libs/libjson-c compile
 make[3] -C package/utils/lua compile
 make[3] -C package/libs/libubox compile
 make[3] -C package/system/ubus compile
 make[3] -C package/system/uci compile
 make[3] -C package/network/config/netifd compile
 make[3] -C package/system/opkg host-compile
 make[3] -C package/system/ubox compile
 make[3] -C package/libs/lzo compile
 make[3] -C package/libs/zlib compile
 make[3] -C package/libs/ncurses compile
 make[3] -C package/utils/util-linux compile
 make[3] -C package/utils/ubi-utils compile
 make[3] -C package/system/procd compile
 make[3] -C package/utils/jsonfilter compile
 make[3] -C package/base-files compile
 make[3] -C package/kernel/gpio-button-hotplug compile
 make[3] -C package/firmware/linux-firmware compile
 make[3] -C package/kernel/linux compile
 make[3] -C package/network/services/hostapd compile
 make[3] -C package/network/utils/iw compile
 make[3] -C package/kernel/mac80211 compile
 make[3] -C package/network/utils/iptables compile
 make[3] -C package/network/config/firewall compile
 make[3] -C package/network/config/swconfig compile
 make[3] -C package/network/ipv6/odhcp6c compile
 make[3] -C package/libs/gmp compile
 make[3] -C package/libs/nettle compile
 make[3] -C package/network/services/dnsmasq compile
 make[3] -C package/network/services/dropbear compile
 make[3] -C package/network/services/odhcpd compile
 make[3] -C package/libs/libpcap compile
 make[3] -C package/network/utils/linux-atm compile
 make[3] -C package/network/utils/resolveip compile
 make[3] -C package/network/services/ppp compile
 make[3] -C package/network/utils/iproute2 compile
 make[3] -C package/network/utils/iwinfo compile
 make[3] -C package/system/fstools compile
 make[3] -C package/system/mtd compile
 make[3] -C package/libs/ocf-crypto-headers compile
 make[3] -C package/libs/openssl compile
 make[3] -C package/system/opkg compile
 make[3] -C package/utils/busybox compile
 make[3] -C package/utils/nvram compile
 make[3] -C package/libs/uclibc++ compile
 make[3] -C package/zerotier compile
make -r world: build failed. Please re-run make with V=s to see what's going on
/home/virtual/openwrt/include/toplevel.mk:171: návod pro cíl „world“ selhal

**Comment by mwarning** [comment]
I did a fresh checkout&build and it works for me.
These target option were selected:

Target System (Broadcom BCM47xx/53xx (MIPS))
Target Profile (Broadcom SoC, all Ethernet, BCM43xx WiFi (b43, default))

Is that what you tried?

**Comment by mwarning** [comment]
I compared the compiler lines, there are identical with mine.

**Comment by 2senel** [comment]
Yes, I also tried "wl proprietary" profile and result for me is same. I also installed fresh Ubuntu and Debian in Parallels (with all dependencies).

Error is still same. Not sure what I'm doing wrong though...

**Comment by mwarning** [comment]
Ok, I was able to finally reproduce the problem. I used a Debian 7.8 netinstall. :-)

**Comment by mwarning** [comment]
It is a good idea to use the correct path. :>

**Comment by 2senel** [comment]
OK, I set up new clean Debian 7.8 netinst machine (in vmware), installed all dependencies, set correct PATH (based on openwrt wiki article), followed instructions and still I'm stuck on compiling zerotier package.

Can you please point me to right direction?

http://pastebin.com/KZSTqkrs

**Comment by mwarning** [comment]
I think I fixed it, please try again.

**Comment by 2senel** [comment]
Finally managed to compile package. The error was caused by missing libopenssl package. :-) Thanks!

**Comment by mwarning** [comment]
I had messed up the include path a second time and had the impression that OpenWrt compiles in a chroot. It is all fine now. :-)
