### ISSUE TITLE
allowDefault=true causes ZT0 interface to go offline

### ISSUE THREAD

**Issue by wealthwatcher** [mwarning/zerotier-openwrt#31]
I'm trying to get my router to send all traffic for connected devices through the Zerotier-assigned default gateway.  When the setting allowDefault=true is enabled via zerotier-cli, the ZT0 interface goes offline and can't be reconnected until after a reboot.

**Comment by mwarning** [comment]
Hm, what Zerotier, LEDE or openwrt version did you use? What model / platform did you try?

**Comment by wealthwatcher** [comment]
Zerotier 1.1.14
Lede Reboot (17.01.4, r3560-79f57e422d)
[GL-AR300M NAND](https://gl-inet.com/docs/mini/ar300m/)

**Comment by mwarning** [comment]
Maybe it was fixed by now?
