### ISSUE TITLE
##ATTENTION!!!##Installing ZeroTier On Your LEDE

### ISSUE THREAD

**Issue by mixzine** [mwarning/zerotier-openwrt#32]
I download and installed zerotier_1.2.8-1_mipsel_24kc.ipk
Then i found The config fiile /etc/config/zerotier is wrong
By correct it should look something like this:
`config zerotier 'default'
        option enabled '1'
        option interface 'wan'
        list join '8056c2e21c000001'
        option secret 'some_really_long_hex_string'`

**Comment by mixzine** [comment]
This is the wrong config
`	
root@LEDE:/etc/config# cat zerotier 

	config zerotier sample_config
	option enabled 0

	# persistent configuration folder (for ZT controller mode)
	#option config_path '/etc/zerotier'

	#option port '9993'

	# Generate secret on first start
	option secret 'generate'

	# Join a public network called Earth
	list join '8056c2e21c000001'
`

**Comment by mwarning** [comment]
Hi @mixzine, 'generate' will be replaced by some_really_long_hex_string when start zerotier.

**Comment by mixzine** [comment]
我已经在LEDE上装好了1.2.8.1 完美
