### ISSUE TITLE
Having a Client pass through and be assigned IP By ZeroTier

### ISSUE THREAD

**Issue by Jbbrack03** [mwarning/zerotier-openwrt#34]
I installed ZerTier on my R6100. The R6100 is acting as a bridge between my LAN and my ZeroTier Network. My local Lan is on a 192.168.2.xxx subnet. My ZeroTier Network is assigning 172.28.28.xxx. I need a device that connects to my local LAN to be managed directly by the ZeroTier network and receive a 172.28.28.xxx IP. So basically pass through the R6100 to show as a client on Zerotier. Is this possible?

**Comment by mwarning** [comment]
It looks like you need to bridge the zt0 interface with the wireless interface. Or you need to forwarding from 192.168.2.1:9944 to 172.28.28.162:9944: https://wiki.openwrt.org/doc/howto/port.forwarding
