### ISSUE TITLE
Error after installation - "disabled in config"

### ISSUE THREAD

**Issue by arampak** [mwarning/zerotier-openwrt#35]
After downloading and installing with opkg on LEDE Reboot 17.01.4 the following lines are printed in console:
Configuring zerotier.
disabled in config
Previous version (1.1.14) had no such problem.

router TP-LINK TL-WDR3600/4300/4310, Atheros AR9344 rev 2
opkg file: zerotier_1.2.8-1_mips_24kc.ipk

**Comment by mwarning** [comment]
Set "option enabled 1" in /etc/config/zerotier. Looking back, this might no have been a good idea as a solution to a minor problem...
