### ISSUE TITLE
where can i download zerotier-openwrt(1.2.10) for openwrt packages?

### ISSUE THREAD

**Issue by wisfern** [mwarning/zerotier-openwrt#36]
Another release. But without packages for Lede, since the minimum compiler version has been raised.
For OpenWrt packages, look here: https://downloads.openwrt.org/releases/17.01.4/packages/

but i can't find this packages in this url!

**Comment by mwarning** [comment]
Well, I wasn't able to update the Zerotier package for this release, because the dependencies of the newer Zerotier packages changed. Zerotier does build for 17.01.4.
