### ISSUE TITLE
zerotier device names and MTU

### ISSUE THREAD

**Issue by barbabob** [mwarning/zerotier-openwrt#38]
To prevent garbage device names I must keep a file /var/lib/zerotier-one/devicemap. On a start zerotier recreates a whole bunch, and on a stop it removes ALL of it. This makes it unmanagable and it forces needles writes. Please keep some configfile(s) that can set the device name and MTU of that device.  (MTU must be low to keep an ssh connection (A-NAT--NAT-B) possible.)
BTW, zerotier on 18.06.0-rc1/2 and snapshot is disfunctional.   I must use 18.06.0 now.

**Comment by mwarning** [comment]
How do the device names look like? Do you connect to a lot of different networks at once?

Btw. in /etc/config/network you can add an interface section to pin a devices mac and mtu.

**Comment by barbabob** [comment]
On Sat, Dec 22, 2018 at 04:19:48PM -0800, Moritz Warning wrote:
>    How do the device names look like? 

'ztbpafrgg3'  on all devices (DIR-505 running openwrt) and even on
a Raspberry Pi (1&3 running raspbian).

>    Do you connect to a lot of different networks at once?

No. It gets hardly used because the main purpose of zerotier is
emergency backdoor access.  It has to be reliably present.
At the moment I set the mtu by a cronjob every few minutes.
I need that cronjob anyway because the zerotier process always vanishes
after a while for no apparent reason. In openwrt that is.
A dip in the network connection maybe?

>    Btw. in /etc/config/network you can add an interface section
>    to pin a devices mac and mtu.

Good to know. I'll give it a try.

Regards, Wim.

**Comment by mwarning** [comment]
Feel free to reopen the issue if the problem is not solved yet.
