### ISSUE TITLE
Error message when compile in openwrt

### ISSUE THREAD

**Issue by a2940uw** [mwarning/zerotier-openwrt#4]
Hi Master, I have follow your instruction to compile the zerotier package for openwrt in ubuntu 15.05 but I face the error is follow, would you tell me how to solve this, thank you so much.

-----
 make[1] package/zerotier/compile
 make[2] -C package/libs/toolchain compile
make -r package/zerotier/compile: build failed. Please re-run make with -j1 V=s to see what's going on
make: *** [package/zerotier/compile] Error 1
-----

**Comment by mwarning** [comment]
Could you please try "make -j1 V=s" and post the error message?

**Comment by a2940uw** [comment]
If try make -j1 V=s
-----
d/openwrt$ make package/zerotier/compile -j1 V=s
make[1]: Entering directory `/home/a2940uw/openwrt_build/openwrt'
make[2]: Entering directory `/home/a2940uw/openwrt_build/openwrt/package/libs/toolchain'
cp -fpR /home/a2940uw/openwrt_build/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/lib/libuClibc-*.so /home/a2940uw/openwrt_build/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/lib/libcrypt-*.so /home/a2940uw/openwrt_build/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/lib/libm-*.so /home/a2940uw/openwrt_build/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/lib/libpthread-*.so /home/a2940uw/openwrt_build/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2/toolchain/
cp: cannot stat '/home/a2940uw/openwrt_build/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/lib/libuClibc-*.so': No such file or directory
cp: cannot stat '/home/keith/openwrt_build/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/lib/libcrypt-*.so': No such file or directory
cp: cannot stat '/home/a2940uw/openwrt_build/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/lib/libm-*.so': No such file or directory
cp: cannot stat '/home/a2940uw/openwrt_build/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/lib/libpthread-*.so': No such file or directory
make[2]: *** [/home/a2940uw/openwrt_build/openwrt/build_dir/target-mips_34kc_uClibc-0.9.33.2/toolchain/.built] Error 1
make[2]: Leaving directory `/home/a2940uw/openwrt_build/openwrt/package/libs/toolchain'
make[1]: *** [package/libs/toolchain/compile] Error 2
make[1]: Leaving directory `/home/a2940uw/openwrt_build/openwrt'
make: *** [package/zerotier/compile] Error 2

-----

**Comment by mwarning** [comment]
@a2940uw: It seems not to be related to ZerotTier. Try `make download` first and see if you have got all packages.

**Comment by mwarning** [comment]
Fixed :-)
