### ISSUE TITLE
Cannot autostart multiple networks

### ISSUE THREAD

**Issue by pulento** [mwarning/zerotier-openwrt#40]
Have the following config to connect two networks:

```
config zerotier 'net1'
	option enabled '1'
	option secret 'secret'
	list join 'somenet'

config zerotier 'net2'
	option enabled '1'
	option secret 'secret'
	list join 'anothernet'
```

On reboot only 'net2' starts, manually joining the 'net1' works and if I comment following line: 

https://github.com/mwarning/zerotier-openwrt/blob/9dbf19e25d9f5d4a5f4b428a2c4eb70de9635291/zerotier/files/zerotier.init#L20

Both networks are started on restart. Seems like removing the config folder every time a instance starts has the consequence that only the last net autostart.

**Comment by mwarning** [comment]
yeah, this looks like a bug. I haven't properly tested starting multiple networks.

**Comment by mwarning** [comment]
Here is a fix: https://github.com/mwarning/zerotier-openwrt/commit/f8894c21ccdbc45fe46cbcac8fdfb429c6608bef

Can you test it?

**Comment by mwarning** [comment]
My own testing says that the problem is fixed. Please reopen if it does not work for you.

**Comment by pulento** [comment]
No :( cannot reopen because you closed it

I end with this directory structure:

```
lrwxrwxrwx    1 root     root            29 Sep  2 14:48 zerotier-one -> /var/lib/zerotier-one_net2/
drwxr-xr-x    3 root     root           120 Sep  2 14:48 zerotier-one_net2/
drwxr-xr-x    4 root     root           180 Sep  2 14:48 zerotier-one_net1/
```

Oddly now just 'net1' autostarts and zerotier-cli nags:

```
root@cf-fb86:/tmp/lib# zerotier-cli info
zerotier-cli: missing port and zerotier-one.port not found in /var/lib/zerotier-one
```

Then I manually fixed the port file but auth token is missing also:

```
echo 9993 > /var/lib/zerotier-one/zerotier-one.port
root@cf-fb86:/# zerotier-cli join net2
401 join {}
```

Since zerotier-one just look /var/lib/zerotier/networks.d we need a way that both nets end up there not on different directories am I right ?

**Comment by pulento** [comment]
Actually no, but I did reboot between tests. Also just commenting the line I mentioned you can maintain multiple networks just running one zerotier-one instance the same as the stock Linux/MacOS clietn:

```
root@cf-fb86:/# zerotier-cli listnetworks
200 listnetworks <nwid> <name> <mac> <status> <type> <dev> <ZT assigned ips>
200 listnetworks 2c33c11230c4a4da net1 da:9c:6f:e7:03:54 OK PRIVATE zt2lrqk2qk 192.168.100.63/24
200 listnetworks 4d71944404b2bfa0 net2 a2:87:19:33:59:06 OK PRIVATE ztrf2sck5e 172.26.0.2/16
root@cf-fb86:/# pgrep zero
2805
```

Forcing different ports do autostart both networks but I do get two zerotier-one process and I have to change config paths with -D for cli as you stated.

Question is why this would be better than just avoid the removal of /var/lib/zerotier on start (is on tmpfs anyway) and let both networks be managed by one daemon as I think upstream developers designed it.

**Comment by mwarning** [comment]
Having multiple networks by instance is the common way to work with zerotier and should work.
Just add multiple `list join '<network_id>'` items to your section in `/etc/config/zerotier`.

**Comment by mwarning** [comment]
Example:
```
config zerotier 'net1'
	option enabled '1'
	option secret 'secret'
	list join 'somenet'
	list join 'someothernet'
```

**Comment by pulento** [comment]
:)

Now I get it. I just moved my config to:

```
config zerotier 'net1'
	option enabled '1'
	option secret 'secret'
	list join 'somenet'
	list join 'anothernet'
```

And it works fine. Your solution is more generic. I image one could connect one instance to the public Zerotier (and multiple networks inside it) and another to a private Zerotier but I haven't see a config parameter to point the client to a different "Control Plane".

Thanks for your clarification !
