### ISSUE TITLE
NEW ID AND ADDRESS AFTER EACH REBOOT

### ISSUE THREAD

**Issue by SuoaJ** [mwarning/zerotier-openwrt#44]
I compiled Openwrt with support for Zerotier as described in the readme of this Git post. My issue now is that a new address and entry is generated on myzerotier.com each time the router is rebooted? How is this resolved? This is my
/etc/config/zerotier;

> config zerotier 'mgmt_net'
> option enabled '1'
> option secret 'generate'
> list join 'my network id'

Edit: The MAC address of the virtual Zerotier adapter also changes with every reboot.

**Comment by SuoaJ** [comment]
Should a new Zerotier interface be created everytime the router is rebooted? The problem with that is one has to go the the Zerotier page each time the device is rebooted to authorise the new address. This does not happen on my Raspberry Pi or Android phone where I also have Zerotier installed.

**Comment by mwarning** [comment]
I have never visited the controller page. If the address (MAC?) has be registered, then there needs to be fixed something. But maybe the address can be fixed in /etc/config/network.
```
config interface
  option ifname zt0
  option mac '12:34:56:ab::cd:ef'
```
(not sure if this works)

**Comment by SuoaJ** [comment]
Problem solved. Must have been an issue with my config file. Followed a tutorial I found right here:

https://github.com/mwarning/zerotier-openwrt/issues/7#issuecomment-358949256

`root@LEDE:~# uci set zerotier.lede_network=zerotier
root@LEDE:~# uci set zerotier.lede_network.interface='wan'
root@LEDE:~# uci set zerotier.lede_network.secret="$(cat /var/lib/zerotier-one/identity.secret)"
root@LEDE:~# uci add_list zerotier.lede_network.join='8ad5123ed69d6f69'
root@LEDE:~# uci set zerotier.lede_network.enabled='1'
root@LEDE:~# uci commit zerotier`

Thanks for the help.
