### ISSUE TITLE
HIGH CPU USAGE LEDE 17.01.6

### ISSUE THREAD

**Issue by SuoaJ** [mwarning/zerotier-openwrt#46]
I am currently running Zerotier  1.1.14 on LEDE 17.01.6 on a Linksys EA3500 router. CPU and memory usage by Zerotier seems high all of the time, for example, at 25% and 49%, respectively. I compiled LEDE and Zerotier myself by following the guide in the readme of this repository. I would like to try a later version to see if this solves the problem. How do I upgrade to a later(or latest) version of Zerotier? I thought by adding the line below to feeds.conf.default it would have pull the latest version. Your help is appreciated. Thanks.

`src-git zerotier https://github.com/mwarning/zerotier-openwrt.git`

**Comment by mwarning** [comment]
Maybe this image work for you:
http://downloads.openwrt.org/releases/18.06.1/targets/kirkwood/generic/openwrt-18.06.1-kirkwood-linksys_audi-squashfs-sysupgrade.bin

If successful, install ZT via the ssh console:
```
opkg update
opkg install zerotier
```

**Comment by SuoaJ** [comment]
I have wireless/latency issues with 18.06.1, hence why I am using 17.01.6. By compiling from source, my own version of LEDE, and pulling Zerotier from

`src-git zerotier https://github.com/mwarning/zerotier-openwrt.git`,

shouldn't I end up with the latest version of Zerotier?

**Comment by mwarning** [comment]
You will end up with the latest version of ZT for that release. OpenWrt 18.06.1 has ZT 1.2.8. Lede 17.01.6 comes with ZT 1.1.14.

In this case, to back port ZT is not trivial, since some dependencies would need to be updated as well.

**Comment by SuoaJ** [comment]
Understood. Thanks.
