### ISSUE TITLE
Could bind to the port 9993@Openwrt 18.06, WNDR3800

### ISSUE THREAD

**Issue by paulzhn** [mwarning/zerotier-openwrt#47]
When I tried `zerotier-cli listnetworks`, it turned to `Please check that the service is running and that TCP port 9993 can be contacted via 127.0.0.1.`
There were no anything else to bind this port.I have no idea what's wrong.

**Comment by sijnak** [comment]
I'm all but an expert neither on OpenWRT nor Zerotier, but it seems that you need to enable (for autostart at boot time) and start the zerotier service :

``` shell
/etc/init.d/zerotier enable
/etc/init.d/zerotier start
```

**Comment by mwarning** [comment]
I would agree with @sijnak. ZT does not start by default.
