### ISSUE TITLE
'option interface' meaning

### ISSUE THREAD

**Issue by evilgreen** [mwarning/zerotier-openwrt#48]
Just a quick question - what is the meaning of 
`option interface 'wan'` ?
Is this just a reference to Internet-facing interface which should be used by the client?
So, if one has the interface named wan1 and/or wwan then the desired name should be there?

**Comment by mwarning** [comment]
This was meant to restart ZT when then interface status changes. For example if you pull the WAN cable and attach another one. This option was removed now. I do not think it is needed anymore.
