### ISSUE TITLE
local.conf usage

### ISSUE THREAD

**Issue by evilgreen** [mwarning/zerotier-openwrt#49]
I would like to use local.conf to disable some interfaces, etc. Currently this file will be lost with service disable/enable. Any recommendations?

**Comment by evilgreen** [comment]
this one:
https://www.zerotier.com/manual.shtml#4_2

**Comment by mwarning** [comment]
I see. The option seem to be missing. Feel free to submit a patch to github.com/openwrt/packages

**Comment by evilgreen** [comment]
> Feel free to submit a patch
Sorry, I'm not that good in programming to do this myself.

**Comment by mwarning** [comment]
The configuration allows to set a local configuration file now:
https://github.com/mwarning/zerotier-openwrt/commit/38b12f8e30efdfd0ff80ac52e412922cbd7b8241#diff-6e49885baa4a91cc12f962515e39f40cR11
