### ISSUE TITLE
Every time I reboot new Address

### ISSUE THREAD

**Issue by helio58** [mwarning/zerotier-openwrt#51]
Hi,
Every time I reboot the router getting a new address in my.zerotier.com
Is there a way to have it persistent ?
Thanks

**Comment by kbumsik** [comment]
I'm having exactly same issue now. It did not happen until recently.
After reboot, the zerotier-one client creates a new Zerotier address so Zerotier recognizes it a new device.
Everything else work fine.

**Comment by helio58** [comment]
I m using OpenWrt 18.06.1, r7258-5eb055306f  , Linux OpenWrt 4.14.63 #0 Wed Aug 15 20:42:39 2018 mips GNU/Linux

**Comment by helio58** [comment]
@kbumsik I think I have it working. Here is what I did.
/etc/init.d/zerotier stop
vi /etc/config/zerotier
in the config I add "   option secret 'generate'   "
save and
/etc/init.d/zerotier start
reboot
Now I got the same address. :)

**Comment by mwarning** [comment]
Hi,
 " option secret 'generate' " creates a new key. But the magic value 'generate' was removed in recent openwrt packages. Now key generation is triggered by an empty/missing key.
You might be able to set the IP address and MAC address of the device by using `/etc/config/network`:
```
config interface
  option ifname 'zt0'
  list ipaddr '1.2.3.4'
  option mac '12:34:56:ab::cd:ef'
```
Not sure if this works. I haven't had time for this package lately.

**Comment by mwarning** [comment]
@helio58 did my config line above work?

**Comment by helio58** [comment]
@mwarning Sorry miss your message. I did not use your line. Thanks

**Comment by mwarning** [comment]
ok, but what did you do to solve your issue?

**Comment by helio58** [comment]
This was what i did
/etc/init.d/zerotier stop
vi /etc/config/zerotier
in the config I add " option secret 'generate' "
save and
/etc/init.d/zerotier start
reboot
Now I got the same address. :)

**Comment by mwarning** [comment]
hm, ok. that looks like the default configuration. (Although I removed the magic 'generate' value in the current version)

**Comment by helio58** [comment]
@mwarning Update. Refresh the router install your package follow the wiki . Works now 100%
Thanks

**Comment by internetxhora** [comment]
Hi, in conclusion how can I fix this reboot issue on current openwrt version?
Thanks in advance.

**Comment by ogarcia** [comment]
@internetxhora simply follow the wiki

**Comment by mwarning** [comment]
I do not think the wiki helps here.
@internetxhora is there a secret set in your `/etc/config/zerotier`?

**Comment by internetxhora** [comment]
Yes I´m using secret = ´generate´, but everytime gl-ar750 router reboots, it gets a new ip so I have to login to zerotier and authorize it.




Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

________________________________
De: Moritz Warning <notifications@github.com>
Enviado: Monday, June 17, 2019 6:05:23 AM
Para: mwarning/zerotier-openwrt
CC: internetxhora; Mention
Asunto: Re: [mwarning/zerotier-openwrt] Every time I reboot new Address (#51)


I do not think the wiki helps here.
@internetxhora<https://github.com/internetxhora> is there a secret set in your /etc/config/zerotier?

**Comment by mwarning** [comment]
@internetxhora please to not use that `generate` special secret key. It was a bad idea. The startup script will generate a key and save it in /etc/config/zerotier if there was no secret set (or it is empty).
Btw., what zerotier version do you use?

**Comment by internetxhora** [comment]
1.2.8-2

**Comment by ogarcia** [comment]
@internetxhora as say @mwarning simply remove the line `option secret = 'generate'` in `/etc/config/zerotier`. Next reboot your router and look again in `/etc/config/zerotier`, you must have a new secret line but with a long id, something like `option secret '6b3a5d8678:0:verylooooongline`. Make sure that you have this line in your config before login to zerotier and authorize. It's the unique way to determine that your node is always the same.

**Comment by internetxhora** [comment]
Thank you very much, that fixed the problem.

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

________________________________
De: Óscar García Amor <notifications@github.com>
Enviado: Tuesday, June 18, 2019 2:16:51 AM
Para: mwarning/zerotier-openwrt
CC: internetxhora; Mention
Asunto: Re: [mwarning/zerotier-openwrt] Every time I reboot new Address (#51)


@internetxhora<https://github.com/internetxhora> as say @mwarning<https://github.com/mwarning> simply remove the line option secret = 'generate' in /etc/config/zerotier. Next reboot your router and look again in /etc/config/zerotier, you must have a new secret line but with a long id, something like option secret '6b3a5d8678:0:verylooooongline. Make sure that you have this line in your config before login to zerotier and authorize. It's the unique way to determine that your node is always the same.
