### ISSUE TITLE
No zt0 interface

### ISSUE THREAD

**Issue by Mirodin** [mwarning/zerotier-openwrt#52]
Some details first:

- Router: NETGEAR WNDR3700v4
- Firmware: OpenWrt 18.06.1 r7258-5eb055306f / LuCI openwrt-18.06 branch (git-18.228.31946-f64b152)
- Kernel: 4.9.120

Problem:

There is no zt0 interface after following instructions.

How to reproduce:

I followed the instructions from the wiki page (https://github.com/mwarning/zerotier-openwrt/wiki). After rebooting my router I could ping it from my local LAN, via mobile network from my smartphone and vice versa. However the instructions state there is a zt0 interface I have to cover via a ZT0 interface (to be honest I do not quite understand that part either). But there is no zt0 interface created by zerotier.

Configs:

```
#~> uci show zerotier
zerotier.sample_config=zerotier
zerotier.sample_config.enabled='0'
zerotier.sample_config.secret='generate'
zerotier.sample_config.join='8056c2e21c000001'
zerotier.olymp=zerotier
zerotier.olymp.interface='wan'
zerotier.olymp.secret='1234567890'
zerotier.olymp.enabled='1'
zerotier.olymp.join='1234567890'
```

```
#~> cat /etc/config/zerotier 

config zerotier 'sample_config'
	option enabled '0'
	option secret 'generate'
	list join '8056c2e21c000001'

config zerotier 'olymp'
	option interface 'wan'
	option secret '1234567890'
	option enabled '1'
	list join '1234567890
```

```
#~> ifconfig zt0
ifconfig: zt0: error fetching interface information: Device not found
```

**Comment by Mirodin** [comment]
Ah, I found my mistake. Zerotier does not create a interface zt0 but some `zt<random chars>` which I did not identify at first. Sorry for that.

**Comment by mwarning** [comment]
:-)

**Comment by mwarning** [comment]
I have updated the docs.

**Comment by Mirodin** [comment]
Thanks, that might prevent others from tripping as well :)
