### ISSUE TITLE
Add 9993 port rule in the wiki How-To

### ISSUE THREAD

**Issue by ogarcia** [mwarning/zerotier-openwrt#53]
I think that in wiki how-to must have an entry about "open" ZeroTier port, simply add the following section in `/etc/config/firewall`

```
config rule
	option target 'ACCEPT'
	option proto 'udp'
	option dest_port '9993'
	option name 'Allow-ZeroTier-Inbound'
	option src '*'
```

In other hand, now the zerotier interface has not `zt0` as its name. Since [version 1.2.6][1] it have a `ztXXXXXXXX` pattern :wink: (Device names are now generated deterministically based on network IDs)

[1]: https://github.com/zerotier/ZeroTierOne/blob/master/RELEASE-NOTES.md#2018-04-17----version-126

**Comment by mwarning** [comment]
I've added it to the wiki.
If you like, I can give you access to the wiki and you can organize it as you like. It certainly needs to love.

**Comment by ogarcia** [comment]
Ok. I'll give some love :heart:, but calmly, because a great power carries a great responsibility :joy:

**Comment by mwarning** [comment]
@ogarcia You should have access now (I think that also included commit access - speaking of great responsibility.. :-P).
