### ISSUE TITLE
collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by shengzhexue** [mwarning/zerotier-openwrt#54]
Hi , mwarning , I use openWRT 15.05.1(Chaos Calmer) , the chip architecture is arm_cortex-a7 32bit, The platform is ipq4028 , zerotier version is 1.1.2 , I get the following error:
/home/zhang/work/ipq4028/qca-networking-2016-spf-3-0_qca_oem.git/qsdk/staging_dir/toolchain-arm_cortex-a7_gcc-5.2.0_uClibc-1.0.14_eabi/lib/gcc/arm-openwrt-linux-uclibcgnueabi/5.2.0/libgcc_eh.a(unwind-arm.o): In function `__aeabi_unwind_cpp_pr0':
/home/zhang/work/ipq4028/qca-networking-2016-spf-3-0_qca_oem.git/qsdk/build_dir/toolchain-arm_cortex-a7_gcc-5.2.0_uClibc-1.0.14_eabi/gcc-5.2.0/libgcc/config/arm/unwind-arm.c:494: multiple definition of `__aeabi_unwind_cpp_pr0'
/home/zhang/work/ipq4028/qca-networking-2016-spf-3-0_qca_oem.git/qsdk/staging_dir/toolchain-arm_cortex-a7_gcc-5.2.0_uClibc-1.0.14_eabi/lib/uclibc_nonshared.a(aeabi_unwind_cpp_pr1.o):aeabi_unwind_cpp_pr1.c:(.text.__aeabi_unwind_cpp_pr0+0x0): first defined here
collect2: error: ld returned 1 exit status
make[3]: *** [one] Error 1

**Comment by mwarning** [comment]
You might want to use the new package here and build that for OpenWRT 15.05.1.

**Comment by shengzhexue** [comment]
i use  the lastest   version(1.2.10-1) and get following  error:

controller/EmbeddedNetworkController.o controller/EmbeddedNetworkController.cpp
In file included from controller/../osdep/OSUtils.hpp:58:0,
from controller/EmbeddedNetworkController.hpp:39,
from controller/EmbeddedNetworkController.cpp:40:
controller/../osdep/../ext/json/json.hpp:67:10: error: #error "unsupported GCC version - see https://github.com/nlohmann/json#supported-compilers"
#error "unsupported GCC version - see https://github.com/nlohmann/json#supported-compilers"
^
controller/../osdep/../ext/json/json.hpp: In static member function 'static std::string nlohmann::detail::exception::name(const string&, int)':
controller/../osdep/../ext/json/json.hpp:217:51: error: 'to_string' is not a member of 'std'
return "[json.exception." + ename + "." + std::to_string(id_) + "] ";
^

**Comment by mwarning** [comment]
Ah, right. hm, that is a tricky one.

**Comment by mwarning** [comment]
I just tried to compile "OpenWRT 15.05.1", but my host system is too new.
Please consider to update to OpenWrt 18.06.2.
