### ISSUE TITLE
Backup config file on package reinstallation

### ISSUE THREAD

**Issue by ogarcia** [mwarning/zerotier-openwrt#55]
Today I upgraded my router from _18.06.2_ to _18.06.4_. After the upgrade I install zerotier package and it overwrite `/etc/config/zerotier` instead of call to `resolve_conffiles` and place the default config file as `/etc/config/zerotier-opkg`.

Is important to fix this because in config file is stored the secret key and if the user don't have a backup may have a big problem.

**Comment by ogarcia** [comment]
More info: The directory `/etc/zerotier` is not added to backup. I know that is an optional directory, but as default config directory I think that must be included in backups, or at least, put a big warning in default config file that these directory does not enter in system backups.

**Comment by ogarcia** [comment]
For fix the `/etc/config/zerotier` overwrite I think that simply need to add the following to Makefile.
```
define Package/zerotier/conffiles
/etc/config/zerotier
endef
```

**Comment by mwarning** [comment]
Agreed, that is important. Do you like to submit to https://github.com/openwrt-routing/packages ?

**Comment by mwarning** [comment]
ok, I made a PR: https://github.com/openwrt/packages/pull/9391
