### ISSUE TITLE
installing on OpenWrt 18.06.4

### ISSUE THREAD

**Issue by webradio** [mwarning/zerotier-openwrt#58]
I wonder if I can install zerotier from package on openwrt 18.06.4 mipsel_24kc

LuCI didn't show zerotier under available packages. So I ` wget http://downloads.openwrt.org/releases/18.06.4/packages/mipsel_24kc/packages/zerotier_1.2.12-2_mipsel_24kc.ipk`

Then `opkg install zerotier_1.2.12-2_mipsel_24kc.ipk`:
     * satisfy_dependencies_for: Cannot satisfy the following dependencies for zerotier:
     *      libstdcpp
     *      kmod-tun
     *      ip
     *      libminiupnpc
     *      libnatpmp

**Comment by mwarning** [comment]
You need to do run "opkg update" first. Then "opkg install zerotier".

**Comment by webradio** [comment]
Sure enough, it helped. Thanks!
Did something happen recently? I ran `opkg update` last week (looking for relayd) and assumed that the package info is up to date since then.

**Comment by mwarning** [comment]
Not that I know of. But the packet database will be lost after reboot.
