### ISSUE TITLE
GL-MT300N-V2 build?

### ISSUE THREAD

**Issue by EricZimmerman** [mwarning/zerotier-openwrt#59]
i have a GL-MT300N-V2 running virtual here cloudhub firmware which is LEDE/openwrt based afaik. When i look at the opkg feeds it shows this:

http://downloads.openwrt.org/snapshots/targets/ramips/mt76x8/packages

is it possible to get a built that works for this device?

**Comment by mwarning** [comment]
That directory is for kernel modules only.
You have to look here: http://downloads.openwrt.org/snapshots/packages/mipsel_24kc/packages/

Anyway, you probably want to do this:
```
opkg update
opkg install zerotier
```
