### ISSUE TITLE
Can zerotier-openwrt be used as a moon server?

### ISSUE THREAD

**Issue by bitsly** [mwarning/zerotier-openwrt#60]
I am using version 1.1.x now, but I did not find command  such as`zerotier-idtool initmoon` and `zerotier-idtool genmoon` on it.

Can zerotier-openwrt be used as a moon server?  Whether to support it on version 1.2.x ？

**Comment by bitsly** [comment]
I update my openwrt to version 18.06.4 and use opkg install zerotier version 1.2.12. I find command `zerotier-idtool initmoon` and `zerotier-idtool genmoon` on it.  so zerotier version 1.2.12. can be used as a moon server.

**Comment by mwarning** [comment]
great to hear :)
