### ISSUE TITLE
Updating zerotier version

### ISSUE THREAD

**Issue by denibertovic** [mwarning/zerotier-openwrt#62]
Hey thanks for this. :cake:

I was wondering what would be the correct path to upgrade the zerotier version available in the official package list? 

Currently it's 1.2.12. but that's over a year old. The current release https://github.com/zerotier/ZeroTierOne/releases seems to be 1.4.6.

**Comment by denibertovic** [comment]
Hmm seems to have been already updated here: https://github.com/openwrt/packages/pull/10015

**Comment by Tennyleaz** [comment]
Opkg packages still has 1.2.12 be the latest package. How could I find a newer version ipk file?

**Comment by mwarning** [comment]
The newest version is in the master branch. I will sync it with the repository of the upcoming OpenWrt 19.07 release.
