### ISSUE TITLE
Go offline after some time, can't be online again.

### ISSUE THREAD

**Issue by Tennyleaz** [mwarning/zerotier-openwrt#63]
I am using zerotier 1.4.6 on openwrt x86 19.07.0 rc2.

I was able to setup and connect to zerotier server at my first setup. After a few days, zerotier shows offline like:

````bash
root@OpenWrt:~# zerotier-cli status
200 info af81xxxxxx 1.4.6 OFFLINE

root@OpenWrt:~# zerotier-cli listnetworks
200 listnetworks <nwid> <name> <mac> <status> <type> <dev> <ZT assigned ips>
200 listnetworks 9bee8941xxxxxxxx  8a:50:59:5b:4c:a3 REQUESTING_CONFIGURATION PRIVATE zt3jnvdpr5 -

root@OpenWrt:~# zerotier-cli listpeers
200 listpeers <ztaddr> <path> <latency> <version> <role>
200 listpeers 34e0a5e174 - -1 - PLANET
200 listpeers 3a46f1bf30 - -1 - PLANET
200 listpeers 992fcf1db7 - -1 - PLANET
200 listpeers de8950a8b2 - -1 - PLANET

````

I could install zerotier-one on Windows PC and successfully connect to my network id, in the same local network.

I tried rebooting openwrt router, run `zerotier-cli leave 9bee8941xxxxxxxx` and join again, but still shows offline.

How could I fix this on openwrt?

**Comment by mwarning** [comment]
It would help if someone could confirm that problem.

**Comment by ogarcia** [comment]
@Tennyleaz Check that you have open 9993 port in UDP for your ZeroTier interface

**Comment by wosk** [comment]
Very often I got the the same issue.

I have
openwrt 21.02
zerotier 1.6.6

I have firewall rule for accept packets on 9993 port but there are no incoming traffic for this rule acording to firewall statistic page.
Also I have kind of "unstable" connection, I need to press the button on captive portal page each 2 hours to resume Internet routing - I assume it may be a rootcause of the issue.

Rerun zerotier-one daemon solves the issue temporarily.

**Comment by cortices** [comment]
I tried upgrading to OpenWRT 22.03 but still having the issue where Internet dropping out somewhat will cause ZeroTier service to become `OFFLINE`. But running `/etc/init.d/zerotier restart` reports 'disabled by config'. Is there some known way to restart the service without rebooting the whole router every time?

**Comment by wosk** [comment]
the same issue with restart.
stop and start works for me

**Comment by cortices** [comment]
I have discovered the "disabled by config" error was a red herring; it was reporting that about a different second config that is disabled; the working item was silently working. It just took 5 minutes to restart. I will now be adding a cron job to restart the interface since it is having this silently failing issue and nobody seems to know why.

**Comment by ogarcia** [comment]
@Tennyleaz @wosk @cortices still occurs?

**Comment by ogarcia** [comment]
Since this no longer seems to be happening, we are closing the issue. In any case you can open a new one if the problem happens again or there is any other question.
