### ISSUE TITLE
Openwrt is inaccessible after rebooting (after configuring ZeroTier)

### ISSUE THREAD

**Issue by MohammadOmara** [mwarning/zerotier-openwrt#64]
I followed all the steps in this [link](https://github.com/mwarning/zerotier-openwrt/wiki#configure-zerotier-on-your-openwrt-router-using-uci) to install ZeroTier on my openwrt. Yet, when I reached the first (reboot) step, I rebooted then the router became completely inaccessible, neither over Wi-Fi nor over Ethernet. Any reason??

**Comment by mwarning** [comment]
What version of Zerotier do you run?

@ogarcia: does the problem sound familiar by any chance?

**Comment by MohammadOmara** [comment]
@mwarning Unfortunately I can't access the openwrt to check .. but I'm using a GL-iNet router with openwrt 18 and I just download ZeroTier 1 hour ago from gl-inet repos. It should be the latest I guess.

**Comment by ogarcia** [comment]
Mmmm. @MohammadOmara maybe you configure a route or IP range in https://my.zerotier.com that have conflicts with your own network?

For example, if your router IP is 192.168.1.1 look that you not have a _Managed route_ for 192.168.1.0/24 and that the ZeroTier network have other range (for example 192.168.10.0/24).

**Comment by MohammadOmara** [comment]
My router has 2 WiFi interfaces .. the first one is having this pool 192.168.8.0/24 and the second one is having this pool 192.168.9.0/24 .. while my ZeroTier IP range is 10.147.17.X

On a different router (D-Link DWR-921), I managed to reboot the router then access the openwrt .. yet, when having the WAN as a landline DSL, I can remotely access the router .. but when having the WAN as 4G, the 4G interface hangs and can't obtain an IP and hence I can't remotely access the router .. can this be linked to the original problem or it's something far from it?

**Comment by mlavelle42** [comment]
> I followed all the steps in this [link](https://github.com/mwarning/zerotier-openwrt/wiki#configure-zerotier-on-your-openwrt-router-using-uci) to install ZeroTier on my openwrt. Yet, when I reached the first (reboot) step, I rebooted then the router became completely inaccessible, neither over Wi-Fi nor over Ethernet. Any reason??

I'm having the same problem installing on GL.iNet routers - followed procedure precisely and has locked up router consistently every time.

**Comment by mlavelle42** [comment]
More... When downloading zerotier, either from inside Luci or by command line, I get 1.2.8-2. But I notice that your reference sites 1.2.12-2. Which is right?

**Comment by mwarning** [comment]
The newest version for OpenWrt snapshot and 19.07 are at ZeroTier 1.4.6. OpenWrt 18.06 is at ZeroTier 1.2.12.

**Comment by mwarning** [comment]
@MohammadOmara can you try OpenWrt master/snapshot? So we can narrow down the problem.
