### ISSUE TITLE
Joining a moon not preserved across reboots

### ISSUE THREAD

**Issue by bradleydiggs** [mwarning/zerotier-openwrt#67]
When joining a moon using **zerotier-cli orbit moonid moonid** it works perfectly, and even creates the **moons.d** directory inside of **/var/lib/zerotier-one** and places the received **.moon** file in there (so all is well).  However, since it appears most of this is created each time, it is therefore missing upon reboot, meaning you must re-issue the orbit command on the next boot to get it to happen again.  Could there be a way to incorporate the orbit command into the **/etc/config/zerotier** file, or something like that to enable persistence?  I tried **list orbit 'moonid moonid'** in the config file just for kicks, but no dice.  Thanks!!  :)

**Comment by mwarning** [comment]
The config file does not support moons, but feel free to add support and submit a pull request.
(sorry, I don't have much time)

**Comment by bradleydiggs** [comment]
No problem!  Good to know.  Thank you so much for the response.  I'm not much of a programmer, unfortunately - but I was able to get it "good enough" by adding (with my moon ID's) to the /etc/rc.local file:

`sleep 300`
`zerotier-cli orbit moonid moonid`

Thank you SO much for the OpenWRT port of this.  It's invaluable.

**Comment by ogarcia** [comment]
@bradleydiggs you can set in `/etc/config/zerotier` an option `config_path` to store persistent data. For example:
```
config zerotier 'myfancynetwork'
	option enabled '1'
	option config_path '/etc/zerotier'
	list join 'networkid'
	option secret 'supersecret'
```

With above config you have set a directoy `/etc/zerotier` where all data is stored and persist across reboots. Next you simple do the `zerotier-cli orbit moonid moonid` once and it works forever :wink:

**Comment by mwarning** [comment]
Ah, right! That should work. :D

**Comment by bradleydiggs** [comment]
Works perfectly!!  For anyone reading just be sure to mkdir the **config_path** directory ahead of time because it appears to symlink over to it but won't actually create it for you.  Once you do that everything works automatically!!  Thanks guys!!  :)
