### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by dogoepp** [mwarning/zerotier-openwrt#68]
Hi, and thanks for your work packaging ZeroTier for OpenWRT.

I just got it to work on a new router, but I have the impression that there is no support for IPv6 within the ZeroTier network.

I'm rather a beginner in the networking domain, so I might have missed something. However, I searched through the knowledge base of ZeroTier, the issues here and on the internet, finding nothing.

Technical information:

- Zerotier 1.2.8-2
- OpenWrt 18.06.1 (GL.iNet's version ?)
- GL.iNet AR750S router

Merci d'avance pour votre aide :-)

**Comment by mwarning** [comment]
ZeroTier supports IPv6. Please provide more details on what is missing / not working for you.

**Comment by dogoepp** [comment]
You're right, and sorry, I gave too little context. 

On my laptop I both get an IPv6 and an IPv4 from ZeroTier, and I can reach other nodes on the ZeroTier network either with their IP v4 or v6. Here is what an `ip address` gives:
```
11: ztzlghxxxx: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2800 qdisc fq_codel state UNKNOWN group default qlen 1000
    link/ether 36:06:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
    inet 172.22.xxx.xxx/16 brd 172.22.255.255 scope global ztzlghxxxx
       valid_lft forever preferred_lft forever
    inet6 fdxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx/88 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::xxxx:xxxx:fe22:77f2/64 scope link 
       valid_lft forever preferred_lft forever
```
(I hope I did not redact too much. Again, I don't really know what kind of information should be protected here.)

However, on the router, the ZeroTier interface never gets an IPv6. As an example, here is an output of `ip address` on the router: 
```
9: ztzlghxxxx: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2800 qdisc fq_codel state UNKNOWN group default qlen 1000
    link/ether 36:1b:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
    inet 172.22.xxx.xxx/16 brd 172.22.255.255 scope global ztzlghxxxx
       valid_lft forever preferred_lft forever
```
Of course, this node can only ping ZeroTier peers through their IPv4

Besides, I did not manage have the router WAN interface get an IPv6 from my home's ISP router. I don't think that this should be a problem though, as other devices on the ZeroTier network are connected to IPv4-only LANs.

**Comment by ogarcia** [comment]
@dogoepp by default ZeroTier works well with IPv6 in OpenWRT, but is possible that you have disabled all IPv6 support in your router if your ISP doesn't support it

Anyway not is necessary to have IPv6 in your wan interface to have it on ZT so check if you have enabled IPv6 support in your router

**Comment by dogoepp** [comment]
I don't know how to enable or disable IPv6 on OpenWRT (despite searching the documentation) but a reset of all settings to default settings for OpenWRT does not bring IPv6.

May I ask how to check whether IPv6 is enabled ? I know that it's more of an OpenWRT question than ZeroTier-OpenWRT one so if you prefer I'll ask on their forum.

**Comment by ogarcia** [comment]
@dogoepp to enable or disable IPv6 in OpenWRT there are several ways. Frist see that you have IPv6 modules loaded in your kernel with `lsmod` command. You must see thinks like _nf_conntrack_ipv6_ or _ip6_tables_.

Look into `/etc/rc.local` and if you have lines like `net.ipv6.conf.all.disable_ipv6` or `net.ipv6.conf.default.disable_ipv6` comment it.

The most important thing is that the command `ip -6 a` must return at least fe80:: addresses and in `lo` interface some like this:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 state UNKNOWN qlen 1000
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
```

**Comment by dogoepp** [comment]
Thanks for the pointers. I do have modules for IPv6 loaded, including *nf_conntrack_ipv6* and *ip6_tables*.

Also, my `/etc/rc.local` file has no line like the ones you mention.

Finally, here is the output of `ip -6 a`:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 state UNKNOWN qlen 1
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 fe80::9683:c4ff:fe00:aa20/64 scope link 
       valid_lft forever preferred_lft forever
```

So I assume that it's not about the router having IPv6 disabled.

**Comment by ogarcia** [comment]
@dogoepp look in ZeroTier Central (my.zerotier.com) that in your network you have enabled (cheked) _ZeroTier 6PLANE (/80 routable for each device)_ to assing IPv6 to every device and make sure that your OpenWRT device has assigned an IPv6

In the other hand. Version 1.2.8 of zerotier is quite old, maybe you must update it to 1.2.12 or (better) 1.4.6

**Comment by dogoepp** [comment]
I had *RFC4193 (/128 for each device)* enabled. Is it preferable to use 6PLANE instead ?

Due to some NAND / NOR issues (as far as I understand) I cannot upgrade OpenWRT yet. It should be possible in the next release. is it possible nonetheless to install newer versions of ZeroTier on OpenWRT 18.06.1 ?

**Comment by ogarcia** [comment]
> I had _RFC4193 (/128 for each device)_ enabled. Is it preferable to use 6PLANE instead ?

6PLANE is the default in ZT, but it should be indifferent to use one or the other

> Due to some NAND / NOR issues (as far as I understand) I cannot upgrade OpenWRT yet. It should be possible in the next release. is it possible nonetheless to install newer versions of ZeroTier on OpenWRT 18.06.1 ?

Probably not since each version need its shared libs. You can try compile it for your ruter, but I don't recommend it.

**Comment by dogoepp** [comment]
So, is it best to make stick with IPv4 for now and wait for the next release of OpenWRT, hoping that it fixes this for the AR750S ?
