### ISSUE TITLE
Setting allowManaged to false

### ISSUE THREAD

**Issue by soccermitchy** [mwarning/zerotier-openwrt#69]
I'm trying to use ZeroTier to connect to my network with a layer 2 bridge vs a routed layer 3 network. When I did `zerotier-cli set [networkId] allowManaged=0`, it was set successfully, however the setting was removed on reboot. Is there a way to set this setting and have it persist across reboots?

**Comment by ogarcia** [comment]
@soccermitchy see [this][1]

[1]: https://github.com/mwarning/zerotier-openwrt/issues/67#issuecomment-604656259
