### ISSUE TITLE
Improve ZT config file

### ISSUE THREAD

**Issue by ogarcia** [mwarning/zerotier-openwrt#72]
To avoid discuss over commits, better use this issue. Related to https://github.com/zerotier/ZeroTierOne/issues/1240

### Current status
Current config file have the following options:
```
config zerotier sample_config
	option enabled 0
	option port '9993' # ZT UDP listen port
	option config_path '/etc/zerotier' # persistent configuration folder (for ZT controller mode)
	option local_conf '/etc/zerotier.conf' # path to the local.conf
	option secret '' # Generate secret on first start
	list join '8056c2e21c000001' # Join a public network called Earth
```

### Proposal
Instead of use a list of networks use a list of configs to have named networks and can use commands `join` and `leave`

```
config zerotier
	option enabled 0 # Enable or disable full service at startup
	option port '9993' # ZT UDP listen port
	option config_path '/etc/zerotier' # persistent configuration folder (for ZT controller mode)
	option local_conf '/etc/zerotier.conf' # path to the local.conf
	option secret '' # Take note that you have only one secret that identifies the client

config network 'earth'
	option enabled 0 # Enable or disable this config at startup
	option id '8056c2e21c000001'

config network 'mynetwork'
	option enabled 0 # Enable or disable this config at startup
	option id '8056c2e21c000011'
```

### Benefits of proposal
* Is more easy to understand? :thinking: 
* You can have named networks in same instance
* You can select if want connect to networks at startup or not in same instance

### Proposal problems
* You lose the possibility of have several instances of ZT (several clients or a separated controller)

**Comment by mwarning** [comment]
Sorry for the delay. I will look into this again this weekend.

**Comment by mwarning** [comment]
It seems to be a good idea in general, to attach a human readable name to a network id. 

But I do not know if switching between different networks is a common practice with ZT. I have only use ZT with one network so far. If it is, then I would give feature a go. Otherwise, I would advise people to use the ZT command line interface or to script something.

**Comment by glimberg** [comment]
From our experience running, and operating ZeroTier, switching between different networks is not commonplace. Especially since ZeroTier can join multiple networks at once.  It's more of a set it & leave it going all the time thing.

**Comment by ogarcia** [comment]
As say @glimberg switching between different networks not is a common practice. Is more common up an instance and join (with same ID) in multiple networks at once.

I think that better of implement the proposed change is modify the `start_instance()` to can do `/etc/init.d/zerotier start_instance instance_name` by hand. This change only need move the logic of `section_enabled` from `start_instance` to `start_service`. Doing this you can have a command to connect and disconnect by hand without modify the syntax of config file.

**Comment by mwarning** [comment]
Ok, that settles it. I will close the issue.

@ogarcia we can implement that another day. Or feel free to submit a merge request.
