### ISSUE TITLE
arp on br-lan for zerotier servers

### ISSUE THREAD

**Issue by wulfy23** [mwarning/zerotier-openwrt#73]
howdy... user requested adding this to my community build... doing some testing...

noticing some unusual arp requests on br-lan...

103.195.103.66 dev br-lan  FAILED
207.246.73.245 dev br-lan  FAILED
147.75.92.2 dev br-lan  FAILED
50.7.252.138 dev br-lan  FAILED
195.181.173.159 dev br-lan  FAILED
185.180.13.82 dev br-lan  FAILED

**Comment by mwarning** [comment]
I do not really know what to do here. It might be some problem introduced by architecture or system. So I would pass that to upstream (wink @glimberg).
Anyway, it looks like the zerotier interface is bridged to br-lan and then traffic for the Internet is routed over this. Not sure if this is normal.

**Comment by glimberg** [comment]
This might be from ZT trying to discover paths to other nodes. ZeroTier constantly tries to find the best paths between nodes.

**Comment by wulfy23** [comment]
alright then... thanks for the timely responses... i'll play around a little more... if there is any VL2 MTIM implications i'll report back... cheers.

**Comment by wulfy23** [comment]
issue TTL timeout... may as well close
