### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by chirayu-patel** [mwarning/zerotier-openwrt#74]
root@OpenWrt:/tmp# uname -a
Linux OpenWrt 4.4.60 #89 SMP PREEMPT Thu Sep 17 15:30:52 UTC 2020 armv7l GNU/Linux

The OS is QSDK which is based on Chaos Calmer (v15)

root@OpenWrt:/tmp# zerotier-cli info
Segmentation fault
root@OpenWrt:/tmp# zerotier-cli status
Segmentation fault

The zerotier process starts okay, but the above commands fail with segfault.

**Comment by mwarning** [comment]
Zerotier is not available for chaos calmer(OpenWrt 15.05). Where did you get the package from? If it was build for a different release, then it is likely Zerotier won't work.
