### ISSUE TITLE
1.6

### ISSUE THREAD

**Issue by laduke** [mwarning/zerotier-openwrt#76]
Hey mwarning!
Really appreciate you maintaining this package. I hope it's not too much trouble for you. 

https://github.com/zerotier/ZeroTierOne/releases/tag/1.6.0

I think my router can use the new AES acceleration feature, so I'm looking forward to it.

**Comment by mwarning** [comment]
Thanks for the heads up.

https://github.com/openwrt/packages/pull/13971

I will have access to my test router on Monday.

**Comment by mwarning** [comment]
@laduke it would be nice for some of the patches to go upstream. ;-)

**Comment by Mackstoresdotcom** [comment]
openwrt 1043nd zerotier as gateway. 1000mbps lan . 100mbps internet both sides. win 10 both pcs, copy from server at openwrt site to remote (logmein ..11mbps) (zerotier 300kbps) tcp fallback false and peers show direct connection

**Comment by mwarning** [comment]
@Mackstoresdotcom not sure what this has to do with issue. Please create a new one.

**Comment by mwarning** [comment]
There is no ZeroTier 1.6.2 in OpenWrt
