### ISSUE TITLE
1043nd Openwrt as gateway . Low copy speeds win 10 pcs on both sides

### ISSUE THREAD

**Issue by Mackstoresdotcom** [mwarning/zerotier-openwrt#78]
openwrt 1043nd zerotier as gateway. 1000mbps lan . 100mbps internet both sides. win 10 both pcs, copy from server at openwrt site to remote (logmein ..11mbps) (zerotier 300kbps) tcp fallback false and peers show direct connection

**Comment by ogarcia** [comment]
If you have low speed connection you must revise your setup. Look if you have the firewall rule set in your router / machines:
```
uci add firewall rule
uci set firewall.@rule[-1].name=Allow-ZeroTier-Inbound
uci set firewall.@rule[-1].src=*
uci set firewall.@rule[-1].target=ACCEPT
uci set firewall.@rule[-1].proto=udp
uci set firewall.@rule[-1].dest_ port=9993
uci commit firewall
```

And that you has not problem with direct port connections from outside.

**Comment by Mackstoresdotcom** [comment]
already was done 
Name: Allow-ZeroTier-Inbound
Protocol: UPD
Source zone: Any zone
Destination zone: Device
Destination port: 9993
acton - accept

and will see
Match:
Incoming IPv4 and IPv6, protocol UDP
From any zone
To this device, port 9993

Action:
Accept input

**Comment by Mackstoresdotcom** [comment]
"And that you has not problem with direct port connections from outside." what does this mean?

**Comment by ogarcia** [comment]
> "And that you has not problem with direct port connections from outside." what does this mean?

Your router **MUST** be directly reached from internet, if you are behind CGNAT (for example) it does not matter what port settings you do because cannot be reached and use a _planet relay_ for connect (more slow).

**Comment by Mackstoresdotcom** [comment]
ah well i have internet coming on mikrotik router that is 11.11.11.254 and this openwrt is 11.11.11.7  in which  gateway is 11.11.11.254 and dns 8.8.8.8 i will try port forward from mikrotik to openwrt.  in open wrt the cli says all connection are direct

**Comment by Mackstoresdotcom** [comment]
I do have a fiber internet but its a dual nat  could that be a problem but for logmein that is not a problem

**Comment by mwarning** [comment]
Zerotier got a few speed improvements for embedded system in the meantime. Please reopen if it is still slow.
