### ISSUE TITLE
HTTP request sent, awaiting response... 404 Not Found

### ISSUE THREAD

**Issue by openwrt-diy** [mwarning/zerotier-openwrt#79]
@mwarning  When compiling the firmware, an error occurred while downloading the DL package!
OpenWrt-19.07.4 + zerotier-1.6.1
Target System (MediaTek Ralink MIPS)  --->
Subtarget (MT7621 based boards)  --->
Target Profile (Phicomm K2P)  --->

make[2]: Entering directory '/home/kokang/19.07.4/feeds/packages/net/zerotier'
mkdir -p /home/kokang/19.07.4/dl
SHELL= flock /home/kokang/19.07.4/tmp/.zerotier-1.6.1.tar.gz.flock -c '  	/home/kokang/19.07.4/scripts/download.pl "/home/kokang/19.07.4/dl" "zerotier-1.6.1.tar.gz" "9ac8adb0b28acf46d8f37f63b46a551ab20d77edf590aceb0b781e3eb5486571" "" "https://codeload.github.com/zerotier/ZeroTierOne/tar.gz/1.6.1?"    '
Can't exec "curl": No such file or directory at /home/kokang/19.07.4/scripts/download.pl line 77.
+ wget --tries=5 --timeout=20 --no-check-certificate --output-document=- https://codeload.github.com/zerotier/ZeroTierOne/tar.gz/1.6.1?/zerotier-1.6.1.tar.gz
--2020-12-01 05:25:22--  https://codeload.github.com/zerotier/ZeroTierOne/tar.gz/1.6.1?/zerotier-1.6.1.tar.gz
Resolving codeload.github.com (codeload.github.com)... 192.30.255.120
Connecting to codeload.github.com (codeload.github.com)|192.30.255.120|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: 'STDOUT'

-                                                [                                                                              <=>           ]  15.28M   254KB/s    in 63s     

2020-12-01 05:26:26 (249 KB/s) - written to stdout [16020443]

Hash of the downloaded file does not match (file: 9e0962a424649cbcbed4e23759e2daa8891feaa51ca0296c53e44976b9e5d652, requested: 9ac8adb0b28acf46d8f37f63b46a551ab20d77edf590aceb0b781e3eb5486571) - deleting download.
Can't exec "curl": No such file or directory at /home/kokang/19.07.4/scripts/download.pl line 77.
+ wget --tries=5 --timeout=20 --no-check-certificate --output-document=- https://sources.openwrt.org/zerotier-1.6.1.tar.gz
--2020-12-01 05:26:26--  https://sources.openwrt.org/zerotier-1.6.1.tar.gz
Resolving sources.openwrt.org (sources.openwrt.org)... 148.251.151.136, 2a01:4f8:210:5087::2
Connecting to sources.openwrt.org (sources.openwrt.org)|148.251.151.136|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-12-01 05:26:27 ERROR 404: Not Found.

Download failed.
Can't exec "curl": No such file or directory at /home/kokang/19.07.4/scripts/download.pl line 77.
+ wget --tries=5 --timeout=20 --no-check-certificate --output-document=- https://mirror2.openwrt.org/sources/zerotier-1.6.1.tar.gz
--2020-12-01 05:26:27--  https://mirror2.openwrt.org/sources/zerotier-1.6.1.tar.gz
Resolving mirror2.openwrt.org (mirror2.openwrt.org)... 46.4.11.11, 2a01:4f8:221:3d45::2
Connecting to mirror2.openwrt.org (mirror2.openwrt.org)|46.4.11.11|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-12-01 05:26:29 ERROR 404: Not Found.

Download failed.
No more mirrors to try - giving up.
Makefile:82: recipe for target '/home/kokang/19.07.4/dl/zerotier-1.6.1.tar.gz' failed
make[2]: *** [/home/kokang/19.07.4/dl/zerotier-1.6.1.tar.gz] Error 2
make[2]: Leaving directory '/home/kokang/19.07.4/feeds/packages/net/zerotier'
time: package/feeds/packages/zerotier/download#0.43#1.54#66.52
package/Makefile:111: recipe for target 'package/feeds/packages/zerotier/download' failed
make[1]: *** [package/feeds/packages/zerotier/download] Error 2
make[1]: Leaving directory '/home/kokang/19.07.4'
make[1]: Entering directory '/home/kokang/19.07.4'
make[2]: Entering directory '/home/kokang/19.07.4/target/linux'
make[3]: Entering directory '/home/kokang/19.07.4/target/linux/ramips'
make[3]: Nothing to be done for 'download'.
make[3]: Leaving directory '/home/kokang/19.07.4/target/linux/ramips'
make[2]: Leaving directory '/home/kokang/19.07.4/target/linux'
time: target/linux/download#0.03#0.20#0.23
make[1]: Leaving directory '/home/kokang/19.07.4'
kokang@virtual-machine:~/19.07.4$

**Comment by mwarning** [comment]
It looks like the package changed. I have two source packages with different sizes but the same content.

**Comment by mwarning** [comment]
https://github.com/openwrt/packages/pull/14090
