### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Aboe646** [mwarning/zerotier-openwrt#8]
Hey, after the update to the latest version (1.1.12) I get the following error:

[207868.474072] zerotier-one[32346]: segfault at 8 ip 0000000000406627 sp 00007ff0dddcdfb0 error 6 in zerotier-one[400000+84000

Sometimes right after I (re)start the service, sometimes after a day or so.
I reinstalled the packages already.

I use openWRT 15.05.1 x86_64

**Comment by mwarning** [comment]
Looks like a bug in ZT. I will try to find it.

**Comment by hajoscher** [comment]
I compiled for ar71xx and have the same issue, crash after random time. Not sure however if it is exactly the same.

**Comment by Aboe646** [comment]
I'm testing some things, and it seems (for now) that the connection is stable. I changed the ip in "my.zerotier.com" to the ip from the bridge in openwrt (the ip from the webinterface).

**Comment by mwarning** [comment]
I found out that the crash occurs in SelfAwareness::getSymmetricNatPredictions().
So far I do not know why.

**Comment by mwarning** [comment]
@adamierymenko any help is appreciated :-)

**Comment by mwarning** [comment]
It looks like this line crashes:
std::vector<InetAddress> sym(RR->sa->getSymmetricNatPredictions());

**Comment by mwarning** [comment]
Should be fixed in the new 1.1.14 release.
