### ISSUE TITLE
Where can I get the 1.6.2 package

### ISSUE THREAD

**Issue by rhuddlestone** [mwarning/zerotier-openwrt#80]
Hi

First, thanks for maintaining this software for OpenWRT.  I have just started using it and I like the features.  

Where can I find an installable package for the 1.6.2 version you updated a few days ago.  I have been looking for days and can not find it anywhere.

Thanks Again

Rob

**Comment by mwarning** [comment]
Try `opkg update` and then `opkg search zerotier`. Also, ZeroTier fails to build on some platforms. This is still under investigation.

**Comment by rhuddlestone** [comment]
Thanks for the answer.  I found it.
