### ISSUE TITLE
Package not available in OpenWRT 19.07.1 anymore

### ISSUE THREAD

**Issue by i40sys** [mwarning/zerotier-openwrt#81]
Do you have any idea about why is not available the package of Zerotier in the release 19.07.1 of OpenWRT?. 

Take a look on that:
https://archive.openwrt.org/releases/19.07.2/packages/aarch64_cortex-a53/packages/
there is the package:
zerotier_1.4.6-1_aarch64_cortex-a53.ipk

But in the office repository of packages:
https://downloads.openwrt.org/releases/packages-19.07/aarch64_cortex-a53/packages/
is not available.

Do you know if there is any bug or issue which causes that? 

Thanks in advances for your support.

**Comment by mwarning** [comment]
I do not know. Building the package myself works fine..
