### ISSUE TITLE
new version Zerotier 1.6.2 can't work well in OpenWrt

### ISSUE THREAD

**Issue by guytogay** [mwarning/zerotier-openwrt#83]
I was using version 1.4.6 in Openwrt, it can help let other subnet device reach every device connected to this OpenWrt. but after I upgrade it to 1.6.2, other devices can only reach OpenWrt, can't reach other devices under this OpenWrt.

**Comment by mwarning** [comment]
Maybe some configuration has changed. Maybe The ZeroTier forum can help you: https://discuss.zerotier.com/

**Comment by guytogay** [comment]
Sorry for my poor English. let me explain more. 
I’m using ZeroTier on OpenWrt to join different LAN into one network using “Auto NAT Clients” function. it worked very well when I was using version 1.4.6. That each device under different subnet could ping / reach different subnet devices via this function. But after upgrading to 1.6.2. only OpenWrt can ping OpenWrt but can’t reach all the other subnet devices connecting to OpenWrt. This issue is critical as that means Zerotier lost it’s meaning for OpenWrt. I have to install Zerotier on each subnet device directly because NAT function via OpenWrt is not working.
![2021-02-03 170826](https://user-images.githubusercontent.com/60613436/106835043-89bd1380-66d1-11eb-967e-efa13cdceb81.png)

**Comment by ogarcia** [comment]
I think that you are using a non standard OpenWRT version because in OpenWRT ZeroTier has not a LUCI (web interface) configuration. Did you open a ticket at your device manufacturer?

**Comment by mwarning** [comment]
Closing this, as there is no resolve possible here. This is for the ZeroTier package only. Please open a ticket with OpenWrt or LuCI.
