### ISSUE TITLE
Package not available in OpenWRT 19.07.6 for arch armvirt/64

### ISSUE THREAD

**Issue by fakuivan** [mwarning/zerotier-openwrt#86]
I'm not sure what the issue is but I was not able to install zerotier using ``opkg``, this installation is using the default package lists, they were not modified. Does this package have some sort of compatibility problem with the aarch64 architecture? Would it be possible to compile from source for this platform? I'm running OpenWRT as a VM with a raspberry pi as a host, previously installing zerotier with openwrt directly on the host was not an issue.

``/etc/openwrt_release``:
```shell
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='19.07.6'
DISTRIB_REVISION='r11278-8055e38794'
DISTRIB_TARGET='armvirt/64'
DISTRIB_ARCH='aarch64_generic'
DISTRIB_DESCRIPTION='OpenWrt 19.07.6 r11278-8055e38794'
DISTRIB_TAINTS=''
```

**Comment by mwarning** [comment]
What zerotier package did you try to install? Is it meant for OpenWrt 19.07.6?

**Comment by ogarcia** [comment]
@fakuivan maybe you want [this](https://downloads.openwrt.org/snapshots/packages/aarch64_generic/packages/zerotier_1.6.2-2_aarch64_generic.ipk)

The full list of packages for aarch64 is [here](https://downloads.openwrt.org/snapshots/packages/aarch64_generic/packages/)

**Comment by fakuivan** [comment]
> What zerotier package did you try to install? Is it meant for OpenWrt 19.07.6?

Just ran ``opkg update && opkg install zerotier``

**Comment by fakuivan** [comment]
> @fakuivan maybe you want [this](https://downloads.openwrt.org/snapshots/packages/aarch64_generic/packages/zerotier_1.6.2-2_aarch64_generic.ipk)
> 
> The full list of packages for aarch64 is [here](https://downloads.openwrt.org/snapshots/packages/aarch64_generic/packages/)

Interesting... Does this mean the package lists are not set up correctly for this build of openwrt? Will these packages work for stable versions? From what I can see those packages are for the snapshot builds.

**Comment by mwarning** [comment]
> > What zerotier package did you try to install? Is it meant for OpenWrt 19.07.6?
> 
> Just ran `opkg update && opkg install zerotier`

That is the preferred way and should work.

**Comment by fakuivan** [comment]
So the [pkgdata page for this](https://openwrt.org/packages/pkgdata/zerotier) states that aarch64_generic is not a supported architecture, in contrast to [jq](https://openwrt.org/packages/pkgdata/jq), a package I was able to install without issues. I guess this worked on "bare metal" since the openwrt build for the raspberry pi runs a 32 bit kernel. Will there need to be patched added for aarch64?

**Comment by mwarning** [comment]
Actually I do not know. But ZeroTier 1.6.3 is under way and fixes some build issues. Maybe that helps.
See https://github.com/openwrt/packages/pull/14677

**Comment by mwarning** [comment]
OpenWrt 19.07.7 has the package: https://downloads.openwrt.org/releases/19.07.7/packages/aarch64_generic/packages/
