### ISSUE TITLE
Stucked in REALY mode when connect to router, but can DIRECT to the PC behind it

### ISSUE THREAD

**Issue by Dango233** [mwarning/zerotier-openwrt#88]
I have to admit this is a weird situation:
I can DIRECT connect to my PC running Zerotier behind my OpenWRT router using the PC Zerotier address, but I can only RELAY to the OpenWRT router running Zerotier session.

I can confirm that the UDP port 9993 has been opened on my router and the routing has been appropriately configured.

Any idea on what's happening?

**Comment by ogarcia** [comment]
I don't understand the situation. Can you explain better? Connections from and to, IPs, etc.

**Comment by nickdsb** [comment]
> 

hello, have you resolved this problem? I met same problem with yours. 
I have 3 peers: 
  one is openwrt router,
  one is PC in router LAN, 
  one is PC outside the router LAN. 
PC to PC is DIRECT , 
but outside-PC ping router is RELAY

**Comment by ogarcia** [comment]
@Dango233 @Derstood still occurs?

**Comment by ogarcia** [comment]
Since this no longer seems to be happening, we are closing the issue. In any case you can open a new one if the problem happens again or there is any other question.
