### ISSUE TITLE
feature request: support MOON peers in the configuration file

### ISSUE THREAD

**Issue by SadPencil** [mwarning/zerotier-openwrt#91]
In a regular Linux distro, path `/var/lib/zerotier-one/moons.d` folder contains the information of MOON peers, each `*.moon` file per peer.
When zerotier service starts, these files are loaded.

Currently, to let the zerotier node join the MOON in openwrt, the only way is to specify `config_path` in your configuration file.
```
# persistent configuration folder (for ZT controller mode)
	#option config_path '/etc/zerotier'
```
and place the moon files inside the folder. 
However, there are some cons in this method. Zerotier writes temporary files in the configuration folder and the persistent storage space in a OpenWRT router should not be written too much as it is a simple SPI flash that can't support too much write. 

See the next comment for my solution.

**Comment by SadPencil** [comment]
This request can be also achieved as follows.

The current behavior `config_path` is make a symlink from `/var/lib/zerotier-one` to `/etc/zerotier`. However, it can be improved by something like,
```
option config_path '/etc/zerotier'
option copy_config true # default to false in order to be compatible with older version's config
```
and instead of making a symlink, copy all the files from `/etc/zerotier` to `/var/lib/zerotier-one`, and initialize the rest files.

**Comment by ogarcia** [comment]
@SadPencil the only _temporally_ files that ZT creates in `/etc/zerotier` are `zerotier-one.pid` and `zerotier-one.port`. Both with size of 4K and only rewrite on a router reboot. I think that flash can manage this without problem.

**Comment by SadPencil** [comment]
> 
> 
> @SadPencil the only _temporally_ files that ZT creates in `/etc/zerotier` are `zerotier-one.pid` and `zerotier-one.port`. Both with size of 4K and only rewrite on a router reboot. I think that flash can manage this without problem.

The temporally files are small, indeed. But I create a PR for this anyhow. Tested on my router.
https://github.com/mwarning/zerotier-openwrt/pull/92

**Comment by SadPencil** [comment]
@ogarcia For those SPI flash without wear leveling feature, even though the files are small, minimizing the write is meaningful. Please review PR #92 .

**Comment by ogarcia** [comment]
@mwarning what do you think?

**Comment by mwarning** [comment]
I will take a look later this week. @SadPencil thank you for your contribution!

**Comment by openwrtdiy** [comment]
@mwarning support MOON?

**Comment by mwarning** [comment]
This feature sounds nice, but since I have never used mooons, it takes some time to grook and to have time to get into it. I hope to have time soon. Thank you for all the contributions so far! :)
