### ISSUE TITLE
openwrt-3.10.14    ,barrier_breaker/14.07/

### ISSUE THREAD

**Issue by zhoulizhengithub** [mwarning/zerotier-openwrt#96]
^
In file included from controller/../osdep/OSUtils.hpp:46:0,
                 from controller/EmbeddedNetworkController.hpp:34,
                 from controller/EmbeddedNetworkController.cpp:38:
controller/../osdep/../ext/json/json.hpp:26358:13: note: 'template<template<class, class, class ...> class ObjectType, template<class, class ...> class ArrayType, class StringType, class BooleanType, class NumberIntegerType, class NumberUnsignedType, class NumberFloatType, template<class> class AllocatorType, template<class, class> class JSONSerializer, class BinaryType> std::string nlohmann::to_string(const nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType>&)' declared here, later in the translation unit
 std::string to_string(const NLOHMANN_BASIC_JSON_TPL& j)
             ^
In file included from controller/../osdep/OSUtils.hpp:46:0,
                 from controller/EmbeddedNetworkController.hpp:34,
                 from controller/EmbeddedNetworkController.cpp:38:
controller/../osdep/../ext/json/json.hpp:4370:29: error: no matching function for call to 'to_string(std::size_t&)'
     target = to_string(value);
                             ^
controller/../osdep/../ext/json/json.hpp:4370:29: note: candidate is:
In file included from controller/../osdep/OSUtils.hpp:46:0,
                 from controller/EmbeddedNetworkController.hpp:34,
                 from controller/EmbeddedNetworkController.cpp:38:
controller/../osdep/../ext/json/json.hpp:26358:13: note: template<template<class, class, class ...> class ObjectType, template<class, class ...> class ArrayType, class StringType, class BooleanType, class NumberIntegerType, class NumberUnsignedType, class NumberFloatType, template<class> class AllocatorType, template<class, class> class JSONSerializer, class BinaryType> std::string nlohmann::to_string(const nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType>&)
 std::string to_string(const NLOHMANN_BASIC_JSON_TPL& j)
             ^
controller/../osdep/../ext/json/json.hpp:26358:13: note:   template argument deduction/substitution failed:
In file included from controller/../osdep/OSUtils.hpp:46:0,
                 from controller/EmbeddedNetworkController.hpp:34,
                 from controller/EmbeddedNetworkController.cpp:38:
controller/../osdep/../ext/json/json.hpp:4370:29: note:   mismatched types 'const nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType>' and 'std::size_t {aka unsigned int}'
     target = to_string(value);
                             ^
In file included from controller/../osdep/OSUtils.hpp:46:0,
                 from controller/EmbeddedNetworkController.hpp:34,
                 from controller/EmbeddedNetworkController.cpp:38:
controller/../osdep/../ext/json/json.hpp: In static member function 'static std::string nlohmann::detail::exception::name(const string&, int)':
controller/../osdep/../ext/json/json.hpp:2668:5: warning: control reaches end of non-void function [-Wreturn-type]
     }
     ^
<builtin>: recipe for target 'controller/EmbeddedNetworkController.o' failed
make[3]: *** [controller/EmbeddedNetworkController.o] Error 1
make[3]: Leaving directory '/home/zhoulizhen/OpenWrt-7620/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/ZeroTierOne-1.8.4'
Makefile:79: recipe for target '/home/zhoulizhen/OpenWrt-7620/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/ZeroTierOne-1.8.4/.built' failed
make[2]: *** [/home/zhoulizhen/OpenWrt-7620/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/ZeroTierOne-1.8.4/.built] Error 2
make[2]: Leaving directory '/home/zhoulizhen/OpenWrt-7620/feeds/zerotier/zerotier'
package/Makefile:173: recipe for target 'package/feeds/zerotier/zerotier/compile' failed
make[1]: *** [package/feeds/zerotier/zerotier/compile] Error 2
make[1]: Leaving directory '/home/zhoulizhen/OpenWrt-7620'
/home/zhoulizhen/OpenWrt-7620/include/toplevel.mk:164: recipe for target 'package/zerotier/compile' failed

编不过可以支持一下吗，这个有点老

**Comment by mwarning** [comment]
hi, you try to compile ZeroTier for a really old OpenWrt release.
It is possible, but quite a lot of work. I have to leave that to you.
