### ISSUE TITLE
Can you support the compilation of this source code? Openwrt-3.10.14

### ISSUE THREAD

**Issue by zhoulizhengithub** [mwarning/zerotier-openwrt#97]
}
     ^
<builtin>: recipe for target 'controller/EmbeddedNetworkController.o' failed
make[3]: *** [controller/EmbeddedNetworkController.o] Error 1
make[3]: Leaving directory '/home/zhoulizhen/route/openwrt-3.10.14/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/ZeroTierOne-1.8.4'
Makefile:79: recipe for target '/home/zhoulizhen/route/openwrt-3.10.14/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/ZeroTierOne-1.8.4/.built' failed
make[2]: *** [/home/zhoulizhen/route/openwrt-3.10.14/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/ZeroTierOne-1.8.4/.built] Error 2
make[2]: Leaving directory '/home/zhoulizhen/route/openwrt-3.10.14/feeds/zerotier/zerotier'
package/Makefile:173: recipe for target 'package/feeds/zerotier/zerotier/compile' failed
make[1]: *** [package/feeds/zerotier/zerotier/compile] Error 2
make[1]: Leaving directory '/home/zhoulizhen/route/openwrt-3.10.14'
/home/zhoulizhen/route/openwrt-3.10.14/include/toplevel.mk:171: recipe for target 'package/zerotier/compile' failed

**Comment by mwarning** [comment]
Sorry mate, I do not support such an old OpenWrt version.

**Comment by zhoulizhengithub** [comment]
> Sorry mate, I do not support such an old OpenWrt version.

Thank you. I have finished the processing and can use it normally
