### ISSUE TITLE
how to compile latest ZT??

### ISSUE THREAD

**Issue by mbunal** [mwarning/zerotier-openwrt#98]
i tried to compile latest ZT accoring to your diectives on github page. but every time compiled with OW version 1.6.6. i cant choose your latest 1.8.4. how can i choose latest version to compile and embed in firmware???

**Comment by mwarning** [comment]
I will update this project later this day.

**Comment by mbunal** [comment]
Waiting Impatiently.…

**Comment by mwarning** [comment]
I have update this repository so far. Waiting for OpenWrt.

**Comment by mwarning** [comment]
If you have ZT 1.6.6, then it means your are using the latest OpenWrt release. The newer versions are in the development version of OpenWrt so far and they need be backported. That is rather easy, but I wait for the Merge Request to be accepted.

**Comment by mbunal** [comment]
> If you have ZT 1.6.6, then it means your are using the latest OpenWrt release. The newer versions are in the development version of OpenWrt so far and they need be backported. That is rather easy, but I wait for the Merge Request to be accepted.


how can i backport?

**Comment by mwarning** [comment]
You can replace `openwrt/feeds/packages/net/zerotier` with the folder in this repository. Or maybe wait for  this official backport: https://github.com/openwrt/packages/pull/18099

But the next OpenWrt release is not far away, so this may not be of much value.
